BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Applications" (
	"Name"	TEXT NOT NULL,
	"Windows"	TEXT,
	"macOS"	TEXT,
	"Linux"	TEXT
);
CREATE TABLE IF NOT EXISTS "CDevelopmentTools" (
	"Name"	TEXT NOT NULL,
	"Windows"	TEXT,
	"Linux"	TEXT,
	"macOS"	TEXT
);
CREATE TABLE IF NOT EXISTS "PythonDevelopmentTools" (
	"Name"	INTEGER NOT NULL,
	"Windows"	TEXT,
	"Linux"	TEXT,
	"macOS"	TEXT
);
CREATE TABLE IF NOT EXISTS "DevelopmentPacks" (
	"Number"	TEXT NOT NULL,
	"Language"	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "RustDevelopmentTools" (
	"Name"	TEXT NOT NULL,
	"Windows"	TEXT,
	"Linux"	TEXT,
	"macOS"	TEXT
);
CREATE TABLE IF NOT EXISTS "JavaScriptDevelopmentTools" (
	"Name"	TEXT NOT NULL,
	"Windows"	TEXT,
	"Linux"	TEXT,
	"macOS"	TEXT
);
CREATE TABLE IF NOT EXISTS "CppDevelopmentTools" (
	"Name"	TEXT NOT NULL,
	"Windows"	TEXT,
	"Linux"	TEXT,
	"macOS"	TEXT
);
CREATE TABLE IF NOT EXISTS "GoDevelopmentTools" (
	"Name"	TEXT NOT NULL,
	"Windows"	TEXT,
	"Linux"	TEXT,
	"macOS"	TEXT
);
CREATE TABLE IF NOT EXISTS "RubyDevelopmentTools" (
	"Name"	TEXT NOT NULL,
	"Windows"	TEXT,
	"Linux"	TEXT,
	"macOS"	TEXT
);
CREATE TABLE IF NOT EXISTS "CSDevelopmentTools" (
	"Name"	TEXT NOT NULL,
	"Windows"	TEXT,
	"Linux"	TEXT,
	"macOS"	TEXT
);
CREATE TABLE IF NOT EXISTS "PHPDevelopmentTools" (
	"Name"	TEXT NOT NULL,
	"Windows"	TEXT,
	"Linux"	TEXT,
	"macOS"	TEXT
);
CREATE TABLE IF NOT EXISTS "KotlinDevelopmentTools" (
	"Name"	TEXT NOT NULL,
	"Windows"	TEXT,
	"Linux"	TEXT,
	"macOS"	TEXT
);
CREATE TABLE IF NOT EXISTS "JavaDevelopmentTools" (
	"Name"	TEXT NOT NULL,
	"Windows"	TEXT,
	"Linux"	TEXT,
	"macOS"	TEXT
);
CREATE TABLE IF NOT EXISTS "Test" (
	"Name"	TEXT NOT NULL,
	"Windows"	TEXT,
	"macOS"	TEXT,
	"Linux"	TEXT
);
CREATE TABLE IF NOT EXISTS "SupportedOS" (
	"Name"	TEXT NOT NULL,
	"PackageManager"	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "PackagesFromSource" (
	"Name"	TEXT NOT NULL,
	"Url"	TEXT,
	"WindowsDir"	TEXT NOT NULL,
	"LinuxDir"	TEXT NOT NULL,
	"macOSDir"	TEXT NOT NULL,
	"Url_arm64"	TEXT,
	"apt"	TEXT,
	"yum"	TEXT,
	"dnf"	TEXT,
	"apk"	TEXT,
	"pacman"	TEXT,
	"zypper"	TEXT
);
INSERT INTO "Applications" ("Name","Windows","macOS","Linux") VALUES ('VSCode','winget install -e --id Microsoft.VisualStudioCode','brew install --cask visual-studio-code','sudo snap install code --classic'),
 ('Docker','winget install -e --id Docker.DockerDesktop','brew install --cask docker','sudo snap install docker'),
 ('Git','winget install --id Git.Git -e --source winget','brew install --cask git','ManualInstallation'),
 ('JetBrains WebStorm','winget install -e --id JetBrains.WebStorm','brew install --cask webstorm','sudo snap install webstorm --classic'),
 ('Postman','winget install -e --id Postman.Postman','brew install --cask postman','sudo snap install postman'),
 ('JetBrains RubyMine','winget install -e --id JetBrains.RubyMine','brew install --cask rubymine','sudo snap install postman'),
 ('JetBrains CLion','winget install -e --id JetBrains.CLion','brew install --cask clion','sudo snap install clion --classic'),
 ('JetBrains DataGrip','winget install -e --id JetBrains.DataGrip','brew install --cask datagrip','sudo snap install datagrip --classic'),
 ('JetBrains DataSpell','winget install -e --id JetBrains.DataSpell','brew install --cask dataspell','sudo snap install dataspell --classic'),
 ('Eclipse IDE','ManualInstallation','brew install --cask eclipse-ide','sudo snap install eclipse --classic'),
 ('JetBrains GoLand','winget install -e --id JetBrains.GoLand','brew install --cask goland','sudo snap install goland --classic'),
 ('JetBrains IntelliJ IDEA Community','winget install -e --id JetBrains.IntelliJIDEA.Community','brew install --cask intellij-idea-ce','sudo snap install intellij-idea-community --classic'),
 ('JetBrains IntelliJ IDEA Ultimate','winget install -e --id JetBrains.IntelliJIDEA.Ultimate','brew install --cask intellij-idea','sudo snap install intellij-idea-ultimate --classic'),
 ('JetBrains Rider','winget install -e --id JetBrains.Rider','brew install --cask rider','sudo snap install rider --classic'),
 ('JetBrains PhpStorm','winget install -e --id JetBrains.PHPStorm','brew install --cask phpstorm','sudo snap install phpstorm --classic'),
 ('JetBrains Space','winget install -e --id JetBrains.Space','brew install --cask jetbrains-space','sudo snap install space'),
 ('Postgresql','winget install -e --id PostgreSQL.PostgreSQL','brew install postgresql@14','sudo snap install postgresql10'),
 ('PgAdmin','winget install -e --id PostgreSQL.pgAdmin','brew install --cask pgadmin4','ManualInstallation'),
 ('Ngrok','winget install -e --id Ngrok.Ngrok','brew install --cask ngrok','sudo snap install ngrok'),
 ('Sublime Text','winget install -e --id SublimeHQ.SublimeText.4','brew install --cask sublime-text','sudo snap install sublime-text --classic'),
 ('JetBrains PyCharm Community','winget install -e --id JetBrains.PyCharm.Community','brew install --cask pycharm-ce','sudo snap install pycharm-community --classic'),
 ('JetBrains PyCharm Proffessional','winget install -e --id JetBrains.PyCharm.Professional','brew install --cask pycharm','sudo snap install pycharm-professional --classic'),
 ('Discord','winget install -e --id Discord.Discord','brew install --cask discord','sudo snap install discord'),
 ('Telegram','winget install -e --id Telegram.TelegramDesktop','brew install --cask telegram','sudo snap install telegram-desktop'),
 ('NodeJS','winget install -e --id OpenJS.NodeJS','brew install node','sudo snap install node --classic'),
 ('Go','winget install -e --id GoLang.Go.1.18','brew install go','sudo snap install go --classic'),
 ('JDK 18','winget install -e --id Oracle.JDK.18','brew install openjdk@18','sudo snap install openjdk@18'),
 ('JDK 19','winget install -e --id Oracle.JDK.19','brew install openjdk@19','sudo snap install openjdk@19'),
 ('Visual Studio Community','winget install -e --id Microsoft.VisualStudio.2022.Community.Preview','Not Found','Not Found'),
 ('Visual Studio Proffessional','winget install -e --id Microsoft.VisualStudio.2022.Professional.Preview','Not Found','Not Found'),
 ('Visual Studio','Not Found','brew install --cask visual-studio','Not Found'),
 ('Rust','winget install -e --id Rustlang.Rust.MSVC','brew install rust','sudo snap install rustup --classic'),
 ('Ruby','winget install -e --id RubyInstallerTeam.Ruby.3.1','brew install ruby','sudo snap install ruby --classic'),
 ('.Net Framework','winget install -e --id Microsoft.DotNet.Framework.DeveloperPack_4','brew install dotnet','sudo snap install dotnet-sdk --classic'),
 ('Python 3.9','winget install -e --id Python.Python.3.9','brew install python@3.9','ManualInstallation'),
 ('Python 3.10','winget install -e --id Python.Python.3.10','brew install python@3.10','ManualInstallation'),
 ('Python 3.11','winget install -e --id Python.Python.3.11','brew install python@3.11','ManualInstallation'),
 ('Vim','winget install -e --id vim.vim','brew install vim','sudo snap install vim-editor --beta'),
 ('NeoVim','winget install -e --id Neovim.Neovim','brew install neovim','sudo snap install nvim --classic'),
 ('vcpkg','ManualInstallation','brew install vcpkg','ManualInstallation'),
 ('Kotlin','ManualInstallation','brew install kotlin','sudo snap install kotlin --classic'),
 ('PHP','ManualInstallation','brew install php','ManualInstallation'),
 ('CMake','winget install -e --id Kitware.CMake','brew install cmake','sudo snap install cmake --classic'),
 ('Make','ManualInstallation','brew install make','ManualInstallation'),
 ('Conan Package Manager','winget install -e --id JFrog.Conan','brew install conan','ManualInstallation'),
 ('Android Studio','winget install -e --id Google.AndroidStudio','brew install --cask android-studio','sudo snap install android-studio --classic'),
 ('MySQL','winget install -e --id Oracle.MySQL','brew install mysql','sudo snap install mysql --beta'),
 ('SQLite','winget install -e --id SQLite.SQLite','brew install sqlite','ManualInstallation'),
 ('SQLiteBrowser','winget install -e --id DBBrowserForSQLite.DBBrowserForSQLite','brew install --cask db-browser-for-sqlite','sudo snap install sqlitebrowser'),
 ('GNU Emacs','winget install -e --id GNU.Emacs','brew install emacs','sudo snap install emacs --classic'),
 ('Nginx','ManualInstallation','brew install nginx','ManualInstallation'),
 ('Wget','ManualInstallation','brew install wget','ManualInstallation'),
 ('MSYS2','winget install -e --id MSYS2.MSYS2','ManualInstallation','ManualInstallation'),
 ('Cygwin','winget install -e --id Cygwin.Cygwin','ManualInstallation','ManualInstallation'),
 ('g++','Not Found','brew install gcc','ManualInstallation'),
 ('gcc','Not Found','brew install gcc','ManualInstallation'),
 ('Nuget','winget install -e --id Microsoft.NuGet','brew install nuget','Not Found'),
 ('GitHub Desktop','winget install -e --id GitHub.GitHubDesktop','brew install --cask github','sudo snap install github-gui'),
 ('GitHub CLI','winget install -e --id GitHub.cli','brew install gh','sudo snap install gh'),
 ('Kubernetes','winget install -e --id Kubernetes.kubectl','brew install kubernetes-cli','sudo snap install kubectl --classic'),
 ('Slack','winget install -e --id SlackTechnologies.Slack','brew install --cask slack','sudo snap install slack');
INSERT INTO "CDevelopmentTools" ("Name","Windows","Linux","macOS") VALUES ('VSCode','winget install -e --id Microsoft.VisualStudioCode','sudo snap install code --classic','brew install --cask visual-studio-code'),
 ('Docker','winget install -e --id Docker.DockerDesktop','sudo snap install docker','brew install --cask docker'),
 ('Git','winget install --id Git.Git -e --source winget','ManualInstallation','brew install --cask git'),
 ('Sublime Text','winget install -e --id SublimeHQ.SublimeText.4','sudo snap install sublime-text --classic','brew install --cask sublime-text'),
 ('Discord','winget install -e --id Discord.Discord','sudo snap install discord','brew install --cask discord'),
 ('Telegram','winget install -e --id Telegram.TelegramDesktop','sudo snap install telegram-desktop','brew install --cask telegram'),
 ('Visual Studio Community','winget install -e --id Microsoft.VisualStudio.2022.Community.Preview','Not Found','Not Found'),
 ('Visual Studio Proffessional','winget install -e --id Microsoft.VisualStudio.2022.Professional.Preview','Not Found','Not Found'),
 ('JetBrains CLion','winget install -e --id JetBrains.CLion','sudo snap install clion --classic','brew install --cask clion'),
 ('vcpkg','ManualInstallation','ManualInstallation','brew install vcpkg'),
 ('JetBrains Space','winget install -e --id JetBrains.Space','sudo snap install space','brew install --cask jetbrains-space'),
 ('Postgresql','winget install -e --id PostgreSQL.PostgreSQL','sudo snap install postgresql10','brew install postgresql@14'),
 ('PgAdmin','winget install -e --id PostgreSQL.pgAdmin','ManualInstallation','brew install --cask pgadmin4'),
 ('Vim','winget install -e --id vim.vim','sudo snap install vim-editor --beta','winget install -e --id vim.vim'),
 ('NeoVim','winget install -e --id Neovim.Neovim','sudo snap install nvim --classic','brew install neovim'),
 ('Visual Studio','Not Found','Not Found','brew install --cask visual-studio'),
 ('JetBrains DataGrip','winget install -e --id JetBrains.DataGrip','sudo snap install datagrip --classic','brew install --cask datagrip'),
 ('JetBrains DataSpell','winget install -e --id JetBrains.DataSpell','sudo snap install dataspell --classic','brew install --cask dataspell'),
 ('CMake','winget install -e --id Kitware.CMake','sudo snap install cmake --classic','brew install cmake'),
 ('Make','ManualInstallation','ManualInstallation','brew install make'),
 ('Conan Package Manager','winget install -e --id JFrog.Conan','ManualInstallation','brew install conan'),
 ('Wget','ManualInstallation','ManualInstallation','brew install wget'),
 ('MySQL','winget install -e --id Oracle.MySQL','sudo snap install mysql --beta','brew install mysql'),
 ('SQLite','winget install -e --id SQLite.SQLite','ManualInstallation','brew install sqlite'),
 ('SQLiteBrowser','winget install -e --id DBBrowserForSQLite.DBBrowserForSQLite','sudo snap install sqlitebrowser','brew install --cask db-browser-for-sqlite'),
 ('GNU Emacs','winget install -e --id GNU.Emacs','sudo snap install emacs --classic','brew install emacs'),
 ('MSYS2','winget install -e --id MSYS2.MSYS2','ManualInstallation','ManualInstallation'),
 ('Cygwin','winget install -e --id Cygwin.Cygwin','ManualInstallation','ManualInstallation'),
 ('g++','Not Found','ManualInstallation','brew install gcc'),
 ('gcc','Not Found','ManualInstallation','brew install gcc'),
 ('GitHub Desktop','winget install -e --id GitHub.GitHubDesktop','sudo snap install github-gui','brew install --cask github'),
 ('GitHub CLI','winget install -e --id GitHub.cli','sudo snap install gh','brew install gh'),
 ('Kubernetes','winget install -e --id Kubernetes.kubectl','sudo snap install kubectl --classic','brew install kubernetes-cli'),
 ('Slack','winget install -e --id SlackTechnologies.Slack','sudo snap install slack','brew install --cask slack');
INSERT INTO "PythonDevelopmentTools" ("Name","Windows","Linux","macOS") VALUES ('VSCode','winget install -e --id Microsoft.VisualStudioCode','sudo snap install code --classic','brew install --cask visual-studio-code'),
 ('Docker','winget install -e --id Docker.DockerDesktop','sudo snap install docker','brew install --cask docker'),
 ('Git','winget install --id Git.Git -e --source winget','ManualInstallation','brew install --cask git'),
 ('Sublime Text','winget install -e --id SublimeHQ.SublimeText.4','sudo snap install sublime-text --classic','brew install --cask sublime-text'),
 ('Discord','winget install -e --id Discord.Discord','sudo snap install discord','brew install --cask discord'),
 ('Telegram','winget install -e --id Telegram.TelegramDesktop','sudo snap install telegram-desktop','brew install --cask telegram'),
 ('Python 3.9','winget install -e --id Python.Python.3.9','ManualInstallation','brew install python@3.9'),
 ('Python 3.10','winget install -e --id Python.Python.3.10','ManualInstallation','brew install python@3.10'),
 ('Python 3.11','winget install -e --id Python.Python.3.11','ManualInstallation','brew install python@3.11'),
 ('JetBrains PyCharm Community','winget install -e --id JetBrains.PyCharm.Community','sudo snap install pycharm-community --classic','brew install --cask pycharm-ce'),
 ('JetBrains PyCharm Proffessional','winget install -e --id JetBrains.PyCharm.Professional','sudo snap install pycharm-professional --classic','brew install --cask pycharm'),
 ('Visual Studio Community','winget install -e --id Microsoft.VisualStudio.2022.Community.Preview','Not Found','Not Found'),
 ('Visual Studio Proffessional','winget install -e --id Microsoft.VisualStudio.2022.Professional.Preview','Not Found','Not Found'),
 ('Postman','winget install -e --id Postman.Postman','sudo snap install postman','brew install --cask postman'),
 ('JetBrains Space','winget install -e --id JetBrains.Space','sudo snap install space','brew install --cask jetbrains-space'),
 ('Postgresql','winget install -e --id PostgreSQL.PostgreSQL','sudo snap install postgresql10','brew install postgresql@14'),
 ('PgAdmin','winget install -e --id PostgreSQL.pgAdmin','ManualInstallation','brew install --cask pgadmin4'),
 ('Vim','winget install -e --id vim.vim','sudo snap install vim-editor --beta','winget install -e --id vim.vim'),
 ('NeoVim','winget install -e --id Neovim.Neovim','sudo snap install nvim --classic','brew install neovim'),
 ('Ngrok','winget install -e --id Ngrok.Ngrok','sudo snap install ngrok','brew install --cask ngrok'),
 ('Visual Studio','Not Found','Not Found','brew install --cask visual-studio'),
 ('JetBrains DataGrip','winget install -e --id JetBrains.DataGrip','sudo snap install datagrip --classic','brew install --cask datagrip'),
 ('JetBrains DataSpell','winget install -e --id JetBrains.DataSpell','sudo snap install dataspell --classic','brew install --cask dataspell'),
 ('Wget','ManualInstallation','ManualInstallation','brew install wget'),
 ('MySQL','winget install -e --id Oracle.MySQL','sudo snap install mysql --beta','brew install mysql'),
 ('SQLite','winget install -e --id SQLite.SQLite','ManualInstallation','brew install sqlite'),
 ('SQLiteBrowser','winget install -e --id DBBrowserForSQLite.DBBrowserForSQLite','sudo snap install sqlitebrowser','brew install --cask db-browser-for-sqlite'),
 ('GNU Emacs','winget install -e --id GNU.Emacs','sudo snap install emacs --classic','brew install emacs'),
 ('Nginx','ManualInstallation','ManualInstallation','brew install nginx'),
 ('GitHub Desktop','winget install -e --id GitHub.GitHubDesktop','sudo snap install github-gui','brew install --cask github'),
 ('GitHub CLI','winget install -e --id GitHub.cli','sudo snap install gh','brew install gh'),
 ('Kubernetes','winget install -e --id Kubernetes.kubectl','sudo snap install kubectl --classic','brew install kubernetes-cli'),
 ('Slack','winget install -e --id SlackTechnologies.Slack','sudo snap install slack','brew install --cask slack');
INSERT INTO "DevelopmentPacks" ("Number","Language") VALUES ('1','PythonDevelopmentTools'),
 ('2','JavaScriptDevelopmentTools'),
 ('3','CppDevelopmentTools'),
 ('4','JavaDevelopmentTools'),
 ('5','GoDevelopmentTools'),
 ('6','RustDevelopmentTools'),
 ('7','RubyDevelopmentTools'),
 ('8','CDevelopmentTools'),
 ('9','CSDevelopmentTools'),
 ('10','PHPDevelopmentTools'),
 ('11','KotlinDevelopmentTools');
INSERT INTO "RustDevelopmentTools" ("Name","Windows","Linux","macOS") VALUES ('VSCode','winget install -e --id Microsoft.VisualStudioCode','sudo snap install code --classic','brew install --cask visual-studio-code'),
 ('Docker','winget install -e --id Docker.DockerDesktop','sudo snap install docker','brew install --cask docker'),
 ('Git','winget install --id Git.Git -e --source winget','ManualInstallation','brew install --cask git'),
 ('Sublime Text','winget install -e --id SublimeHQ.SublimeText.4','sudo snap install sublime-text --classic','brew install --cask sublime-text'),
 ('Discord','winget install -e --id Discord.Discord','sudo snap install discord','brew install --cask discord'),
 ('Telegram','winget install -e --id Telegram.TelegramDesktop','sudo snap install telegram-desktop','brew install --cask telegram'),
 ('Visual Studio Community','winget install -e --id Microsoft.VisualStudio.2022.Community.Preview','Not Found','Not Found'),
 ('Visual Studio Proffessional','winget install -e --id Microsoft.VisualStudio.2022.Professional.Preview','Not Found','Not Found'),
 ('Rust','winget install -e --id Rustlang.Rust.MSVC','sudo snap install rustup --classic','brew install rust'),
 ('Postman','winget install -e --id Postman.Postman','sudo snap install postman','brew install --cask postman'),
 ('JetBrains Space','winget install -e --id JetBrains.Space','sudo snap install space','brew install --cask jetbrains-space'),
 ('Postgresql','winget install -e --id PostgreSQL.PostgreSQL','sudo snap install postgresql10','brew install postgresql@14'),
 ('PgAdmin','winget install -e --id PostgreSQL.pgAdmin','ManualInstallation','brew install --cask pgadmin4'),
 ('Vim','winget install -e --id vim.vim','sudo snap install vim-editor --beta','winget install -e --id vim.vim'),
 ('NeoVim','winget install -e --id Neovim.Neovim','sudo snap install nvim --classic','brew install neovim'),
 ('Ngrok','winget install -e --id Ngrok.Ngrok','sudo snap install ngrok','brew install --cask ngrok'),
 ('Visual Studio','Not Found','Not Found','brew install --cask visual-studio'),
 ('Wget','ManualInstallation','ManualInstallation','brew install wget'),
 ('MySQL','winget install -e --id Oracle.MySQL','sudo snap install mysql --beta','brew install mysql'),
 ('SQLite','winget install -e --id SQLite.SQLite','ManualInstallation','brew install sqlite'),
 ('SQLiteBrowser','winget install -e --id DBBrowserForSQLite.DBBrowserForSQLite','sudo snap install sqlitebrowser','brew install --cask db-browser-for-sqlite'),
 ('GNU Emacs','winget install -e --id GNU.Emacs','sudo snap install emacs --classic','brew install emacs'),
 ('Nginx','ManualInstallation','ManualInstallation','brew install nginx'),
 ('GitHub Desktop','winget install -e --id GitHub.GitHubDesktop','sudo snap install github-gui','brew install --cask github'),
 ('GitHub CLI','winget install -e --id GitHub.cli','sudo snap install gh','brew install gh'),
 ('Kubernetes','winget install -e --id Kubernetes.kubectl','sudo snap install kubectl --classic','brew install kubernetes-cli'),
 ('Slack','winget install -e --id SlackTechnologies.Slack','sudo snap install slack','brew install --cask slack');
INSERT INTO "JavaScriptDevelopmentTools" ("Name","Windows","Linux","macOS") VALUES ('VSCode','winget install -e --id Microsoft.VisualStudioCode','sudo snap install code --classic','brew install --cask visual-studio-code'),
 ('Docker','winget install -e --id Docker.DockerDesktop','sudo snap install docker','brew install --cask docker'),
 ('Git','winget install --id Git.Git -e --source winget','ManualInstallation','brew install --cask git'),
 ('Sublime Text','winget install -e --id SublimeHQ.SublimeText.4','sudo snap install sublime-text --classic','brew install --cask sublime-text'),
 ('Discord','winget install -e --id Discord.Discord','sudo snap install discord','brew install --cask discord'),
 ('Telegram','winget install -e --id Telegram.TelegramDesktop','sudo snap install telegram-desktop','brew install --cask telegram'),
 ('Visual Studio Community','winget install -e --id Microsoft.VisualStudio.2022.Community.Preview','Not Found','Not Found'),
 ('Visual Studio Proffessional','winget install -e --id Microsoft.VisualStudio.2022.Professional.Preview','Not Found','Not Found'),
 ('JetBrains WebStorm','winget install -e --id JetBrains.WebStorm','sudo snap install webstorm --classic','brew install --cask webstorm'),
 ('NodeJS','winget install -e --id OpenJS.NodeJS','sudo snap install node --classic','brew install node'),
 ('Postman','winget install -e --id Postman.Postman','sudo snap install postman','brew install --cask postman'),
 ('JetBrains Space','winget install -e --id JetBrains.Space','sudo snap install space','brew install --cask jetbrains-space'),
 ('Postgresql','winget install -e --id PostgreSQL.PostgreSQL','sudo snap install postgresql10','brew install postgresql@14'),
 ('PgAdmin','winget install -e --id PostgreSQL.pgAdmin','ManualInstallation','brew install --cask pgadmin4'),
 ('Vim','winget install -e --id vim.vim','sudo snap install vim-editor --beta','winget install -e --id vim.vim'),
 ('NeoVim','winget install -e --id Neovim.Neovim','sudo snap install nvim --classic','brew install neovim'),
 ('Ngrok','winget install -e --id Ngrok.Ngrok','sudo snap install ngrok','brew install --cask ngrok'),
 ('Visual Studio','Not Found','Not Found','brew install --cask visual-studio'),
 ('JetBrains DataGrip','winget install -e --id JetBrains.DataGrip','sudo snap install datagrip --classic','brew install --cask datagrip'),
 ('JetBrains DataSpell','winget install -e --id JetBrains.DataSpell','sudo snap install dataspell --classic','brew install --cask dataspell'),
 ('Wget','ManualInstallation','ManualInstallation','brew install wget'),
 ('MySQL','winget install -e --id Oracle.MySQL','sudo snap install mysql --beta','brew install mysql'),
 ('SQLite','winget install -e --id SQLite.SQLite','ManualInstallation','brew install sqlite'),
 ('SQLiteBrowser','winget install -e --id DBBrowserForSQLite.DBBrowserForSQLite','sudo snap install sqlitebrowser','brew install --cask db-browser-for-sqlite'),
 ('GNU Emacs','winget install -e --id GNU.Emacs','sudo snap install emacs --classic','brew install emacs'),
 ('Nginx','ManualInstallation','ManualInstallation','brew install nginx'),
 ('GitHub Desktop','winget install -e --id GitHub.GitHubDesktop','sudo snap install github-gui','brew install --cask github'),
 ('GitHub CLI','winget install -e --id GitHub.cli','sudo snap install gh','brew install gh'),
 ('Kubernetes','winget install -e --id Kubernetes.kubectl','sudo snap install kubectl --classic','brew install kubernetes-cli'),
 ('Slack','winget install -e --id SlackTechnologies.Slack','sudo snap install slack','brew install --cask slack');
INSERT INTO "CppDevelopmentTools" ("Name","Windows","Linux","macOS") VALUES ('VSCode','winget install -e --id Microsoft.VisualStudioCode','sudo snap install code --classic','brew install --cask visual-studio-code'),
 ('Docker','winget install -e --id Docker.DockerDesktop','sudo snap install docker','brew install --cask docker'),
 ('Git','winget install --id Git.Git -e --source winget','ManualInstallation','brew install --cask git'),
 ('Sublime Text','winget install -e --id SublimeHQ.SublimeText.4','sudo snap install sublime-text --classic','brew install --cask sublime-text'),
 ('Discord','winget install -e --id Discord.Discord','sudo snap install discord','brew install --cask discord'),
 ('Telegram','winget install -e --id Telegram.TelegramDesktop','sudo snap install telegram-desktop','brew install --cask telegram'),
 ('Visual Studio Community','winget install -e --id Microsoft.VisualStudio.2022.Community.Preview','Not Found','Not Found'),
 ('Visual Studio Proffessional','winget install -e --id Microsoft.VisualStudio.2022.Professional.Preview','Not Found','Not Found'),
 ('JetBrains CLion','winget install -e --id JetBrains.CLion','sudo snap install clion --classic','brew install --cask clion'),
 ('vcpkg','ManualInstallation','ManualInstallation','brew install vcpkg'),
 ('Postman','winget install -e --id Postman.Postman','sudo snap install postman','brew install --cask postman'),
 ('JetBrains Space','winget install -e --id JetBrains.Space','sudo snap install space','brew install --cask jetbrains-space'),
 ('Postgresql','winget install -e --id PostgreSQL.PostgreSQL','sudo snap install postgresql10','brew install postgresql@14'),
 ('PgAdmin','winget install -e --id PostgreSQL.pgAdmin','ManualInstallation','brew install --cask pgadmin4'),
 ('Vim','winget install -e --id vim.vim','sudo snap install vim-editor --beta','winget install -e --id vim.vim'),
 ('NeoVim','winget install -e --id Neovim.Neovim','sudo snap install nvim --classic','brew install neovim'),
 ('Ngrok','winget install -e --id Ngrok.Ngrok','sudo snap install ngrok','brew install --cask ngrok'),
 ('Visual Studio','Not Found','Not Found','brew install --cask visual-studio'),
 ('JetBrains DataGrip','winget install -e --id JetBrains.DataGrip','sudo snap install datagrip --classic','brew install --cask datagrip'),
 ('JetBrains DataSpell','winget install -e --id JetBrains.DataSpell','sudo snap install dataspell --classic','brew install --cask dataspell'),
 ('CMake','winget install -e --id Kitware.CMake','sudo snap install cmake --classic','brew install cmake'),
 ('Make','ManualInstallation','ManualInstallation','brew install make'),
 ('Conan Package Manager','winget install -e --id JFrog.Conan','ManualInstallation','brew install conan'),
 ('Wget','ManualInstallation','ManualInstallation','brew install wget'),
 ('MySQL','winget install -e --id Oracle.MySQL','sudo snap install mysql --beta','brew install mysql'),
 ('SQLite','winget install -e --id SQLite.SQLite','ManualInstallation','brew install sqlite'),
 ('SQLiteBrowser','winget install -e --id DBBrowserForSQLite.DBBrowserForSQLite','sudo snap install sqlitebrowser','brew install --cask db-browser-for-sqlite'),
 ('GNU Emacs','winget install -e --id GNU.Emacs','sudo snap install emacs --classic','brew install emacs'),
 ('Nginx','ManualInstallation','ManualInstallation','brew install nginx'),
 ('MSYS2','winget install -e --id MSYS2.MSYS2','ManualInstallation','ManualInstallation'),
 ('Cygwin','winget install -e --id Cygwin.Cygwin','ManualInstallation','ManualInstallation'),
 ('g++','Not Found','ManualInstallation','brew install gcc'),
 ('gcc','Not Found','ManualInstallation','brew install gcc'),
 ('GitHub Desktop','winget install -e --id GitHub.GitHubDesktop','sudo snap install github-gui','brew install --cask github'),
 ('GitHub CLI','winget install -e --id GitHub.cli','sudo snap install gh','brew install gh'),
 ('Kubernetes','winget install -e --id Kubernetes.kubectl','sudo snap install kubectl --classic','brew install kubernetes-cli'),
 ('Slack','winget install -e --id SlackTechnologies.Slack','sudo snap install slack','brew install --cask slack');
INSERT INTO "GoDevelopmentTools" ("Name","Windows","Linux","macOS") VALUES ('VSCode','winget install -e --id Microsoft.VisualStudioCode','sudo snap install code --classic','brew install --cask visual-studio-code'),
 ('Docker','winget install -e --id Docker.DockerDesktop','sudo snap install docker','brew install --cask docker'),
 ('Git','winget install --id Git.Git -e --source winget','ManualInstallation','brew install --cask git'),
 ('Sublime Text','winget install -e --id SublimeHQ.SublimeText.4','sudo snap install sublime-text --classic','brew install --cask sublime-text'),
 ('Discord','winget install -e --id Discord.Discord','sudo snap install discord','brew install --cask discord'),
 ('Telegram','winget install -e --id Telegram.TelegramDesktop','sudo snap install telegram-desktop','brew install --cask telegram'),
 ('Visual Studio Community','winget install -e --id Microsoft.VisualStudio.2022.Community.Preview','Not Found','Not Found'),
 ('Visual Studio Proffessional','winget install -e --id Microsoft.VisualStudio.2022.Professional.Preview','Not Found','Not Found'),
 ('JetBrains GoLand','winget install -e --id JetBrains.GoLand','sudo snap install goland --classic','brew install --cask goland'),
 ('Go','winget install -e --id GoLang.Go.1.18','sudo snap install go --classic','brew install go'),
 ('Postman','winget install -e --id Postman.Postman','sudo snap install postman','brew install --cask postman'),
 ('JetBrains Space','winget install -e --id JetBrains.Space','sudo snap install space','brew install --cask jetbrains-space'),
 ('Postgresql','winget install -e --id PostgreSQL.PostgreSQL','sudo snap install postgresql10','brew install postgresql@14'),
 ('PgAdmin','winget install -e --id PostgreSQL.pgAdmin','ManualInstallation','brew install --cask pgadmin4'),
 ('Vim','winget install -e --id vim.vim','sudo snap install vim-editor --beta','winget install -e --id vim.vim'),
 ('NeoVim','winget install -e --id Neovim.Neovim','sudo snap install nvim --classic','brew install neovim'),
 ('Ngrok','winget install -e --id Ngrok.Ngrok','sudo snap install ngrok','brew install --cask ngrok'),
 ('Visual Studio','Not Found','Not Found','brew install --cask visual-studio'),
 ('JetBrains DataGrip','winget install -e --id JetBrains.DataGrip','sudo snap install datagrip --classic','brew install --cask datagrip'),
 ('JetBrains DataSpell','winget install -e --id JetBrains.DataSpell','sudo snap install dataspell --classic','brew install --cask dataspell'),
 ('Wget','ManualInstallation','ManualInstallation','brew install wget'),
 ('MySQL','winget install -e --id Oracle.MySQL','sudo snap install mysql --beta','brew install mysql'),
 ('SQLite','winget install -e --id SQLite.SQLite','ManualInstallation','brew install sqlite'),
 ('SQLiteBrowser','winget install -e --id DBBrowserForSQLite.DBBrowserForSQLite','sudo snap install sqlitebrowser','brew install --cask db-browser-for-sqlite'),
 ('GNU Emacs','winget install -e --id GNU.Emacs','sudo snap install emacs --classic','brew install emacs'),
 ('Nginx','ManualInstallation','ManualInstallation','brew install nginx'),
 ('GitHub Desktop','winget install -e --id GitHub.GitHubDesktop','sudo snap install github-gui','brew install --cask github'),
 ('GitHub CLI','winget install -e --id GitHub.cli','sudo snap install gh','brew install gh'),
 ('Kubernetes','winget install -e --id Kubernetes.kubectl','sudo snap install kubectl --classic','brew install kubernetes-cli'),
 ('Slack','winget install -e --id SlackTechnologies.Slack','sudo snap install slack','brew install --cask slack');
INSERT INTO "RubyDevelopmentTools" ("Name","Windows","Linux","macOS") VALUES ('VSCode','winget install -e --id Microsoft.VisualStudioCode','sudo snap install code --classic','brew install --cask visual-studio-code'),
 ('Docker','winget install -e --id Docker.DockerDesktop','sudo snap install docker','brew install --cask docker'),
 ('Git','winget install --id Git.Git -e --source winget','ManualInstallation','brew install --cask git'),
 ('Sublime Text','winget install -e --id SublimeHQ.SublimeText.4','sudo snap install sublime-text --classic','brew install --cask sublime-text'),
 ('Discord','winget install -e --id Discord.Discord','sudo snap install discord','brew install --cask discord'),
 ('Telegram','winget install -e --id Telegram.TelegramDesktop','sudo snap install telegram-desktop','brew install --cask telegram'),
 ('Visual Studio Community','winget install -e --id Microsoft.VisualStudio.2022.Community.Preview','Not Found','Not Found'),
 ('Visual Studio Proffessional','winget install -e --id Microsoft.VisualStudio.2022.Professional.Preview','Not Found','Not Found'),
 ('JetBrains RubyMine','winget install -e --id JetBrains.RubyMine','sudo snap install postman','brew install --cask rubymine'),
 ('Ruby','winget install -e --id RubyInstallerTeam.Ruby.3.1','sudo snap install ruby --classic','brew install ruby'),
 ('Postman','winget install -e --id Postman.Postman','sudo snap install postman','brew install --cask postman'),
 ('JetBrains Space','winget install -e --id JetBrains.Space','sudo snap install space','brew install --cask jetbrains-space'),
 ('Postgresql','winget install -e --id PostgreSQL.PostgreSQL','sudo snap install postgresql10','brew install postgresql@14'),
 ('PgAdmin','winget install -e --id PostgreSQL.pgAdmin','ManualInstallation','brew install --cask pgadmin4'),
 ('Vim','winget install -e --id vim.vim','sudo snap install vim-editor --beta','winget install -e --id vim.vim'),
 ('NeoVim','winget install -e --id Neovim.Neovim','sudo snap install nvim --classic','brew install neovim'),
 ('Ngrok','winget install -e --id Ngrok.Ngrok','sudo snap install ngrok','brew install --cask ngrok'),
 ('Visual Studio','Not Found','Not Found','brew install --cask visual-studio'),
 ('Wget','ManualInstallation','ManualInstallation','brew install wget'),
 ('MySQL','winget install -e --id Oracle.MySQL','sudo snap install mysql --beta','brew install mysql'),
 ('SQLite','winget install -e --id SQLite.SQLite','ManualInstallation','brew install sqlite'),
 ('SQLiteBrowser','winget install -e --id DBBrowserForSQLite.DBBrowserForSQLite','sudo snap install sqlitebrowser','brew install --cask db-browser-for-sqlite'),
 ('GNU Emacs','winget install -e --id GNU.Emacs','sudo snap install emacs --classic','brew install emacs'),
 ('Nginx','ManualInstallation','ManualInstallation','brew install nginx'),
 ('GitHub Desktop','winget install -e --id GitHub.GitHubDesktop','sudo snap install github-gui','brew install --cask github'),
 ('GitHub CLI','winget install -e --id GitHub.cli','sudo snap install gh','brew install gh'),
 ('Kubernetes','winget install -e --id Kubernetes.kubectl','sudo snap install kubectl --classic','brew install kubernetes-cli'),
 ('Slack','winget install -e --id SlackTechnologies.Slack','sudo snap install slack','brew install --cask slack');
INSERT INTO "CSDevelopmentTools" ("Name","Windows","Linux","macOS") VALUES ('VSCode','winget install -e --id Microsoft.VisualStudioCode','sudo snap install code --classic','brew install --cask visual-studio-code'),
 ('Docker','winget install -e --id Docker.DockerDesktop','sudo snap install docker','brew install --cask docker'),
 ('Git','winget install --id Git.Git -e --source winget','ManualInstallation','brew install --cask git'),
 ('Sublime Text','winget install -e --id SublimeHQ.SublimeText.4','sudo snap install sublime-text --classic','brew install --cask sublime-text'),
 ('Discord','winget install -e --id Discord.Discord','sudo snap install discord','brew install --cask discord'),
 ('Telegram','winget install -e --id Telegram.TelegramDesktop','sudo snap install telegram-desktop','brew install --cask telegram'),
 ('Visual Studio Community','winget install -e --id Microsoft.VisualStudio.2022.Community.Preview','Not Found','Not Found'),
 ('Visual Studio Proffessional','winget install -e --id Microsoft.VisualStudio.2022.Professional.Preview','Not Found','Not Found'),
 ('JetBrains Rider','winget install -e --id JetBrains.Rider','sudo snap install rider --classic','brew install --cask rider'),
 ('.Net Framework','winget install -e --id Microsoft.DotNet.Framework.DeveloperPack_4','sudo snap install dotnet-sdk --classic','brew install dotnet'),
 ('Postman','winget install -e --id Postman.Postman','sudo snap install postman','brew install --cask postman'),
 ('JetBrains Space','winget install -e --id JetBrains.Space','sudo snap install space','brew install --cask jetbrains-space'),
 ('Postgresql','winget install -e --id PostgreSQL.PostgreSQL','sudo snap install postgresql10','brew install postgresql@14'),
 ('PgAdmin','winget install -e --id PostgreSQL.pgAdmin','winget install -e --id PostgreSQL.pgAdmin','brew install --cask pgadmin4'),
 ('Vim','winget install -e --id vim.vim','sudo snap install vim-editor --beta','winget install -e --id vim.vim'),
 ('NeoVim','winget install -e --id Neovim.Neovim','sudo snap install nvim --classic','brew install neovim'),
 ('Ngrok','winget install -e --id Ngrok.Ngrok','sudo snap install ngrok','brew install --cask ngrok'),
 ('Visual Studio','Not Found','Not Found','brew install --cask visual-studio'),
 ('Wget','ManualInstallation','ManualInstallation','brew install wget'),
 ('MySQL','winget install -e --id Oracle.MySQL','sudo snap install mysql --beta','brew install mysql'),
 ('SQLite','winget install -e --id SQLite.SQLite','ManualInstallation','brew install sqlite'),
 ('SQLiteBrowser','winget install -e --id DBBrowserForSQLite.DBBrowserForSQLite','sudo snap install sqlitebrowser','brew install --cask db-browser-for-sqlite'),
 ('GNU Emacs','winget install -e --id GNU.Emacs','sudo snap install emacs --classic','brew install emacs'),
 ('Nginx','ManualInstallation','ManualInstallation','brew install nginx'),
 ('Nuget','winget install -e --id Microsoft.NuGet','Not Found','brew install nuget'),
 ('GitHub Desktop','winget install -e --id GitHub.GitHubDesktop','sudo snap install github-gui','brew install --cask github'),
 ('GitHub CLI','winget install -e --id GitHub.cli','sudo snap install gh','brew install gh'),
 ('Kubernetes','winget install -e --id Kubernetes.kubectl','sudo snap install kubectl --classic','brew install kubernetes-cli'),
 ('Slack','winget install -e --id SlackTechnologies.Slack','sudo snap install slack','brew install --cask slack');
INSERT INTO "PHPDevelopmentTools" ("Name","Windows","Linux","macOS") VALUES ('VSCode','winget install -e --id Microsoft.VisualStudioCode','sudo snap install code --classic','brew install --cask visual-studio-code'),
 ('Docker','winget install -e --id Docker.DockerDesktop','sudo snap install docker','brew install --cask docker'),
 ('Git','winget install --id Git.Git -e --source winget','ManualInstallation','brew install --cask git'),
 ('Sublime Text','winget install -e --id SublimeHQ.SublimeText.4','sudo snap install sublime-text --classic','brew install --cask sublime-text'),
 ('Discord','winget install -e --id Discord.Discord','sudo snap install discord','brew install --cask discord'),
 ('Telegram','winget install -e --id Telegram.TelegramDesktop','sudo snap install telegram-desktop','brew install --cask telegram'),
 ('Visual Studio Community','winget install -e --id Microsoft.VisualStudio.2022.Community.Preview','Not Found','Not Found'),
 ('Visual Studio Proffessional','winget install -e --id Microsoft.VisualStudio.2022.Professional.Preview','Not Found','Not Found'),
 ('JetBrains PhpStorm','winget install -e --id JetBrains.PHPStorm','sudo snap install phpstorm --classic','brew install --cask phpstorm'),
 ('Postman','winget install -e --id Postman.Postman','sudo snap install postman','brew install --cask postman'),
 ('JetBrains Space','winget install -e --id JetBrains.Space','sudo snap install space','brew install --cask jetbrains-space'),
 ('Postgresql','winget install -e --id PostgreSQL.PostgreSQL','sudo snap install postgresql10','brew install postgresql@14'),
 ('PgAdmin','winget install -e --id PostgreSQL.pgAdmin','ManualInstallation','brew install --cask pgadmin4'),
 ('Vim','winget install -e --id vim.vim','sudo snap install vim-editor --beta','winget install -e --id vim.vim'),
 ('NeoVim','winget install -e --id Neovim.Neovim','sudo snap install nvim --classic','brew install neovim'),
 ('Ngrok','winget install -e --id Ngrok.Ngrok','sudo snap install ngrok','brew install --cask ngrok'),
 ('Visual Studio','Not Found','Not Found','brew install --cask visual-studio'),
 ('PHP','ManualInstallation','ManualInstallation','brew install php'),
 ('Wget','ManualInstallation','ManualInstallation','brew install wget'),
 ('MySQL','winget install -e --id Oracle.MySQL','sudo snap install mysql --beta','brew install mysql'),
 ('SQLite','winget install -e --id SQLite.SQLite','ManualInstallation','brew install sqlite'),
 ('SQLiteBrowser','winget install -e --id DBBrowserForSQLite.DBBrowserForSQLite','sudo snap install sqlitebrowser','brew install --cask db-browser-for-sqlite'),
 ('GNU Emacs','winget install -e --id GNU.Emacs','sudo snap install emacs --classic','brew install emacs'),
 ('GitHub Desktop','winget install -e --id GitHub.GitHubDesktop','sudo snap install github-gui','brew install --cask github'),
 ('GitHub CLI','winget install -e --id GitHub.cli','sudo snap install gh','brew install gh'),
 ('Kubernetes','winget install -e --id Kubernetes.kubectl','sudo snap install kubectl --classic','brew install kubernetes-cli'),
 ('Slack','winget install -e --id SlackTechnologies.Slack','sudo snap install slack','brew install --cask slack');
INSERT INTO "KotlinDevelopmentTools" ("Name","Windows","Linux","macOS") VALUES ('VSCode','winget install -e --id Microsoft.VisualStudioCode','sudo snap install code --classic','brew install --cask visual-studio-code'),
 ('Docker','winget install -e --id Docker.DockerDesktop','sudo snap install docker','brew install --cask docker'),
 ('Git','winget install --id Git.Git -e --source winget','ManualInstallation','brew install --cask git'),
 ('Sublime Text','winget install -e --id SublimeHQ.SublimeText.4','sudo snap install sublime-text --classic','brew install --cask sublime-text'),
 ('Discord','winget install -e --id Discord.Discord','sudo snap install discord','brew install --cask discord'),
 ('Telegram','winget install -e --id Telegram.TelegramDesktop','sudo snap install telegram-desktop','brew install --cask telegram'),
 ('Visual Studio Community','winget install -e --id Microsoft.VisualStudio.2022.Community.Preview','Not Found','Not Found'),
 ('Visual Studio Proffessional','winget install -e --id Microsoft.VisualStudio.2022.Professional.Preview','Not Found','Not Found'),
 ('Eclipse IDE','ManualInstallation','sudo snap install eclipse --classic','brew install --cask eclipse-ide'),
 ('Kotlin','ManualInstallation','sudo snap install kotlin --classic','brew install kotlin'),
 ('JetBrains Space','winget install -e --id JetBrains.Space','sudo snap install space','brew install --cask jetbrains-space'),
 ('Postgresql','winget install -e --id PostgreSQL.PostgreSQL','sudo snap install postgresql10','brew install postgresql@14'),
 ('PgAdmin','winget install -e --id PostgreSQL.pgAdmin','ManualInstallation','brew install --cask pgadmin4'),
 ('Vim','winget install -e --id vim.vim','sudo snap install vim-editor --beta','winget install -e --id vim.vim'),
 ('NeoVim','winget install -e --id Neovim.Neovim','sudo snap install nvim --classic','brew install neovim'),
 ('Visual Studio','Not Found','Not Found','brew install --cask visual-studio'),
 ('Wget','ManualInstallation','ManualInstallation','brew install wget'),
 ('Android Studio','winget install -e --id Google.AndroidStudio','sudo snap install android-studio --classic','brew install --cask android-studio'),
 ('MySQL','winget install -e --id Oracle.MySQL','sudo snap install mysql --beta','brew install mysql'),
 ('SQLite','winget install -e --id SQLite.SQLite','ManualInstallation','brew install sqlite'),
 ('SQLiteBrowser','winget install -e --id DBBrowserForSQLite.DBBrowserForSQLite','sudo snap install sqlitebrowser','brew install --cask db-browser-for-sqlite'),
 ('GNU Emacs','winget install -e --id GNU.Emacs','sudo snap install emacs --classic','brew install emacs'),
 ('GitHub Desktop','winget install -e --id GitHub.GitHubDesktop','sudo snap install github-gui','brew install --cask github'),
 ('GitHub CLI','winget install -e --id GitHub.cli','sudo snap install gh','brew install gh'),
 ('Kubernetes','winget install -e --id Kubernetes.kubectl','sudo snap install kubectl --classic','brew install kubernetes-cli'),
 ('Slack','winget install -e --id SlackTechnologies.Slack','sudo snap install slack','brew install --cask slack');
INSERT INTO "JavaDevelopmentTools" ("Name","Windows","Linux","macOS") VALUES ('VSCode','winget install -e --id Microsoft.VisualStudioCode','sudo snap install code --classic','brew install --cask visual-studio-code'),
 ('Docker','winget install -e --id Docker.DockerDesktop','sudo snap install docker','brew install --cask docker'),
 ('Git','winget install --id Git.Git -e --source winget','ManualInstallation','brew install --cask git'),
 ('Sublime Text','winget install -e --id SublimeHQ.SublimeText.4','sudo snap install sublime-text --classic','brew install --cask sublime-text'),
 ('Discord','winget install -e --id Discord.Discord','sudo snap install discord','brew install --cask discord'),
 ('Telegram','winget install -e --id Telegram.TelegramDesktop','sudo snap install telegram-desktop','brew install --cask telegram'),
 ('Visual Studio Community','winget install -e --id Microsoft.VisualStudio.2022.Community.Preview','Not Found','Not Found'),
 ('Visual Studio Proffessional','winget install -e --id Microsoft.VisualStudio.2022.Professional.Preview','Not Found','Not Found'),
 ('JDK 18','winget install -e --id Oracle.JDK.18','sudo snap install openjdk@18','brew install openjdk@18'),
 ('JDK 19','winget install -e --id Oracle.JDK.19','sudo snap install openjdk@19','brew install openjdk@19'),
 ('Eclipse IDE','ManualInstallation','sudo snap install eclipse --classic','brew install --cask eclipse-ide'),
 ('Postman','winget install -e --id Postman.Postman','sudo snap install postman','brew install --cask postman'),
 ('JetBrains Space','winget install -e --id JetBrains.Space','sudo snap install space','brew install --cask jetbrains-space'),
 ('Postgresql','winget install -e --id PostgreSQL.PostgreSQL','sudo snap install postgresql10','brew install postgresql@14'),
 ('PgAdmin','winget install -e --id PostgreSQL.pgAdmin','ManualInstallation','brew install --cask pgadmin4'),
 ('Vim','winget install -e --id vim.vim','sudo snap install vim-editor --beta','winget install -e --id vim.vim'),
 ('NeoVim','winget install -e --id Neovim.Neovim','sudo snap install nvim --classic','brew install neovim'),
 ('Ngrok','winget install -e --id Ngrok.Ngrok','sudo snap install ngrok','brew install --cask ngrok'),
 ('Visual Studio','Not Found','Not Found','brew install --cask visual-studio'),
 ('JetBrains DataGrip','winget install -e --id JetBrains.DataGrip','sudo snap install datagrip --classic','brew install --cask datagrip'),
 ('JetBrains DataSpell','winget install -e --id JetBrains.DataSpell','sudo snap install dataspell --classic','brew install --cask dataspell'),
 ('Wget','ManualInstallation','ManualInstallation','brew install wget'),
 ('Android Studio','winget install -e --id Google.AndroidStudio','sudo snap install android-studio --classic','brew install --cask android-studio'),
 ('MySQL','winget install -e --id Oracle.MySQL','sudo snap install mysql --beta','brew install mysql'),
 ('SQLite','winget install -e --id SQLite.SQLite','ManualInstallation','brew install sqlite'),
 ('SQLiteBrowser','winget install -e --id DBBrowserForSQLite.DBBrowserForSQLite','sudo snap install sqlitebrowser','brew install --cask db-browser-for-sqlite'),
 ('GNU Emacs','winget install -e --id GNU.Emacs','sudo snap install emacs --classic','brew install emacs'),
 ('Nginx','ManualInstallation','ManualInstallation','brew install nginx'),
 ('GitHub Desktop','winget install -e --id GitHub.GitHubDesktop','sudo snap install github-gui','brew install --cask github'),
 ('GitHub CLI','winget install -e --id GitHub.cli','sudo snap install gh','brew install gh'),
 ('Kubernetes','winget install -e --id Kubernetes.kubectl','sudo snap install kubectl --classic','brew install kubernetes-cli'),
 ('Slack','winget install -e --id SlackTechnologies.Slack','sudo snap install slack','brew install --cask slack');
INSERT INTO "SupportedOS" ("Name","PackageManager") VALUES ('Ubuntu','apt'),
 ('Debian GNU/Linux','apt'),
 ('Kali GNU/Linux','apt'),
 ('CentOS Linux','yum'),
 ('Alpine Linux','apk');
INSERT INTO "PackagesFromSource" ("Name","Url","WindowsDir","LinuxDir","macOSDir","Url_arm64","apt","yum","dnf","apk","pacman","zypper") VALUES ('vcpkg','https://github.com/microsoft/vcpkg','C:\','/usr/bin/','Empty','Empty',NULL,NULL,NULL,NULL,NULL,NULL),
 ('Make','Empty','C:\Make','Empty','Empty','Empty','sudo apt update -y && sudo apt install make -y','sudo yum update -y && sudo yum install make -y','sudo dnf -y update && sudo dnf -y install make',NULL,NULL,NULL),
 ('PHP','https://windows.php.net/downloads/releases/php-8.2.9-Win32-vs16-x64.zip','C:\PHP','Empty','Empty','Empty','sudo apt update -y && sudo apt install php -y && sudo apt install libapache2-mod-php -y','sudo yum update -y &&  sudo  yum install epel-release yum-utils -y && sudo yum install http://rpms.remirepo.net/enterprise/remi-release-7.rpm -y &&  sudo yum-config-manager --enable remi-php74 && sudo yum update -y && sudo yum install php -y && sudo yum install php-fpm php-curl php-cli php-json php-mysql php-opcache php-dom php-exif php-fileinfo php-zip php-mbstring php-hash php-imagick php-openssl php-pcre php-xml php-bcmath php-filter php-pear php-gd php-mcrypt php-intl php-iconv php-zlib php-xmlreader -y','sudo dnf -y update && sudo dnf -y install dnf-plugins-core && sudo dnf config-manager --set-enabled remi && sudo dnf module reset php -y && sudo dnf module -y install php:remi-8.0 && sudo dnf -y install php-cli php-fpm php-mysqlnd php-zip php-devel php-gd php-mcrypt php-mbstring php-curl php-xml php-pear php-bcmath php-json && sudo systemctl enable --now php-fpm',NULL,NULL,NULL),
 ('Eclipse IDE','https://mirrors.jevincanders.net/eclipse/technology/epp/downloads/release/2023-06/R/eclipse-java-2023-06-R-win32-x86_64.zip','C:\','Empty','Empty','Empty',NULL,NULL,NULL,NULL,NULL,NULL),
 ('Kotlin','https://github.com/JetBrains/kotlin/releases/download/v1.8.22/kotlin-compiler-1.8.22.zip','C:\','Empty','Empty','Empty',NULL,NULL,NULL,NULL,NULL,NULL),
 ('Wget','https://eternallybored.org/misc/wget/1.21.4/64/wget.exe','C:\Wget','Empty','Empty','Empty','sudo apt update -y && sudo apt install wget -y','sudo yum install wget','sudo dnf -y update && sudo dnf install wget',NULL,NULL,NULL),
 ('Python 3.9','https://github.com/Blackflame576/PythonArchives/releases/download/Python_3.9.6_linux_amd64/Python3.9.6_linux_amd64.zip','Empty','/usr/bin/','Empty','Empty','sudo apt update -y  && sudo apt install software-properties-common -y  &&  sudo add-apt-repository ppa:deadsnakes/ppa && sudo apt update -y && sudo apt install python3.9 -y','sudo yum update -y && sudo yum install epel-release -y && sudo yum install python-pip -y && sudo yum install gcc openssl-devel bzip2-devel libffi-devel zlib-devel -y && wget https://www.python.org/ftp/python/3.9.6/Python-3.9.6.tgz && tar -xvf Python-3.9.6.tgz && ./configure --enable-optimizations && sudo make && sudo make altinstall','sudo dnf -y update && sudo dnf groupinstall ''development tools'' && sudo dnf install wget openssl-devel bzip2-devel libffi-devel &&  sudo curl https://www.python.org/ftp/python/3.9.6/Python-3.9.6.tgz -O &&  tar -xvf Python-3.9.6.tgz && cd Python-3.9.6 &&  sudo ./configure --enable-optimizations && sudo make install',NULL,NULL,NULL),
 ('Python 3.10','https://github.com/Blackflame576/PythonArchives/releases/download/Python_3.10.12_linux_amd64/Python_3.10.12_linux_amd64.zip','Empty','/usr/bin/','Empty','Empty','sudo apt update -y  && sudo apt install software-properties-common -y  &&  sudo add-apt-repository ppa:deadsnakes/ppa && sudo apt update -y  && sudo apt install python3.10 -y','sudo yum update -y && sudo yum install epel-release -y && sudo yum install python-pip -y && sudo yum install gcc openssl-devel bzip2-devel libffi-devel zlib-devel -y && wget https://www.python.org/ftp/python/3.10.12/Python-3.10.12.tgz && tar -xvf Python-3.10.12.tgz && ./configure --enable-optimizations && sudo make && sudo make altinstall','sudo dnf -y update && sudo dnf groupinstall ''development tools'' && sudo dnf install wget openssl-devel bzip2-devel libffi-devel &&  sudo curl https://www.python.org/ftp/python/3.10.12/Python-3.10.12.tgz -O &&  tar -xvf Python-3.10.12.tgz && cd Python-3.10.12 &&  sudo ./configure --enable-optimizations && sudo make install',NULL,NULL,NULL),
 ('Python 3.11','https://github.com/Blackflame576/PythonArchives/releases/download/Python_3.11.4_linux_amd64/Python_3.11.4_linux_amd64.zip','Empty','/usr/bin/','Empty','Empty','sudo apt update -y  && sudo apt install software-properties-common  -y  &&  sudo add-apt-repository ppa:deadsnakes/ppa && sudo apt update -y && sudo apt install python3.11 -y','sudo yum update -y && sudo yum install epel-release -y && sudo yum install python-pip -y && sudo yum install gcc openssl-devel bzip2-devel libffi-devel zlib-devel -y && wget https://www.python.org/ftp/python/3.11.4/Python-3.11.4.tgz && tar -xvf Python-3.11.4.tgz && ./configure --enable-optimizations && sudo make && sudo make altinstall','sudo dnf -y update && sudo dnf groupinstall ''development tools'' && sudo dnf install wget openssl-devel bzip2-devel libffi-devel &&  sudo curl https://www.python.org/ftp/python/3.11.4/Python-3.11.4.tgz -O &&  tar -xvf Python-3.11.4.tgz && cd Python-3.11.4 &&  sudo ./configure --enable-optimizations && sudo make install && ',NULL,NULL,NULL),
 ('Nginx','http://nginx.org/download/nginx-1.25.1.zip','C:\','Empty','Empty','Empty','sudo apt update -y && sudo apt install nginx -y','sudo yum install epel-release -y && sudo yum update -y && sudo yum install nginx','sudo dnf -y update && sudo dnf install nginx && sudo systemctl enable nginx && sudo systemctl start nginx',NULL,NULL,NULL);
COMMIT;
