BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Applications" (
	"id"	INTEGER NOT NULL UNIQUE,
	"Name"	TEXT NOT NULL UNIQUE,
	"Windows"	TEXT NOT NULL,
	"macOS"	TEXT NOT NULL,
	"Linux_amd64"	TEXT NOT NULL,
	"Linux_arm64"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "CDevelopmentTools" (
	"id"	INTEGER NOT NULL UNIQUE,
	"Name"	NUMERIC NOT NULL UNIQUE,
	"Windows"	TEXT NOT NULL,
	"macOS"	TEXT NOT NULL,
	"Linux_amd64"	TEXT NOT NULL,
	"Linux_arm64"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "CSDevelopmentTools" (
	"id"	INTEGER NOT NULL UNIQUE,
	"Name"	NUMERIC NOT NULL UNIQUE,
	"Windows"	TEXT NOT NULL,
	"macOS"	TEXT NOT NULL,
	"Linux_amd64"	TEXT NOT NULL,
	"Linux_arm64"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "CppDevelopmentTools" (
	"id"	INTEGER NOT NULL UNIQUE,
	"Name"	NUMERIC NOT NULL UNIQUE,
	"Windows"	TEXT NOT NULL,
	"macOS"	TEXT NOT NULL,
	"Linux_amd64"	TEXT NOT NULL,
	"Linux_arm64"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "GoDevelopmentTools" (
	"id"	INTEGER NOT NULL UNIQUE,
	"Name"	NUMERIC NOT NULL UNIQUE,
	"Windows"	TEXT NOT NULL,
	"macOS"	TEXT NOT NULL,
	"Linux_amd64"	TEXT NOT NULL,
	"Linux_arm64"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "JavaDevelopmentTools" (
	"id"	INTEGER NOT NULL UNIQUE,
	"Name"	NUMERIC NOT NULL UNIQUE,
	"Windows"	TEXT NOT NULL,
	"macOS"	TEXT NOT NULL,
	"Linux_amd64"	TEXT NOT NULL,
	"Linux_arm64"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "JavaScriptDevelopmentTools" (
	"id"	INTEGER NOT NULL UNIQUE,
	"Name"	NUMERIC NOT NULL UNIQUE,
	"Windows"	TEXT NOT NULL,
	"macOS"	TEXT NOT NULL,
	"Linux_amd64"	TEXT NOT NULL,
	"Linux_arm64"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "KotlinDevelopmentTools" (
	"id"	INTEGER NOT NULL UNIQUE,
	"Name"	NUMERIC NOT NULL UNIQUE,
	"Windows"	TEXT NOT NULL,
	"macOS"	TEXT NOT NULL,
	"Linux_amd64"	TEXT NOT NULL,
	"Linux_arm64"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "PHPDevelopmentTools" (
	"id"	INTEGER NOT NULL UNIQUE,
	"Name"	NUMERIC NOT NULL UNIQUE,
	"Windows"	TEXT NOT NULL,
	"macOS"	TEXT NOT NULL,
	"Linux_amd64"	TEXT NOT NULL,
	"Linux_arm64"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "PythonDevelopmentTools" (
	"id"	INTEGER NOT NULL UNIQUE,
	"Name"	NUMERIC NOT NULL UNIQUE,
	"Windows"	TEXT NOT NULL,
	"macOS"	TEXT NOT NULL,
	"Linux_amd64"	TEXT NOT NULL,
	"Linux_arm64"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "RubyDevelopmentTools" (
	"id"	INTEGER NOT NULL UNIQUE,
	"Name"	NUMERIC NOT NULL UNIQUE,
	"Windows"	TEXT NOT NULL,
	"macOS"	TEXT NOT NULL,
	"Linux_amd64"	TEXT NOT NULL,
	"Linux_arm64"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "RustDevelopmentTools" (
	"id"	INTEGER NOT NULL UNIQUE,
	"Name"	NUMERIC NOT NULL UNIQUE,
	"Windows"	TEXT NOT NULL,
	"macOS"	TEXT NOT NULL,
	"Linux_amd64"	TEXT NOT NULL,
	"Linux_arm64"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "DevelopmentPacks" (
	"id"	INTEGER NOT NULL UNIQUE,
	"Language"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "PackagesFromSource_Linux_amd64" (
	"id"	INTEGER NOT NULL UNIQUE,
	"Name"	TEXT NOT NULL,
	"Url"	TEXT DEFAULT 'Empty',
	"Command"	TEXT DEFAULT 'Empty',
	"apt"	TEXT DEFAULT 'Empty',
	"yum"	TEXT DEFAULT 'Empty',
	"dnf"	TEXT DEFAULT 'Empty',
	"apk"	TEXT DEFAULT 'Empty',
	"pacman"	TEXT DEFAULT 'Empty',
	"zypper"	TEXT DEFAULT 'Empty',
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "PackagesFromSource_Linux_arm64" (
	"id"	INTEGER NOT NULL UNIQUE,
	"Name"	TEXT NOT NULL,
	"Url"	TEXT DEFAULT 'Empty',
	"Command"	TEXT DEFAULT 'Empty',
	"apt"	TEXT DEFAULT 'Empty',
	"yum"	TEXT DEFAULT 'Empty',
	"dnf"	TEXT DEFAULT 'Empty',
	"apk"	TEXT DEFAULT 'Empty',
	"pacman"	TEXT DEFAULT 'Empty',
	"zypper"	TEXT DEFAULT 'Empty',
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "PackagesFromSource_Windows" (
	"id"	INTEGER NOT NULL UNIQUE,
	"Name"	TEXT NOT NULL,
	"Url"	TEXT DEFAULT 'Empty',
	"Command"	TEXT DEFAULT 'Empty',
	"HomeURL"	,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "PackagesFromSource_macOS" (
	"id"	INTEGER NOT NULL UNIQUE,
	"Name"	TEXT NOT NULL,
	"Url"	TEXT DEFAULT 'Empty',
	"Command"	TEXT DEFAULT 'Empty',
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "OS_Commands" (
	"id"	INTEGER NOT NULL UNIQUE,
	"Name"	TEXT NOT NULL,
	"Windows"	TEXT NOT NULL,
	"Linux"	TEXT NOT NULL,
	"macOS"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "SupportedOS" (
	"id"	INTEGER NOT NULL UNIQUE,
	"Name"	TEXT NOT NULL,
	"PackageManager"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Languages" (
	"id"	INTEGER NOT NULL UNIQUE,
	"Name"	INTEGER NOT NULL UNIQUE,
	PRIMARY KEY("id" AUTOINCREMENT)
);
INSERT INTO "Applications" ("id","Name","Windows","macOS","Linux_amd64","Linux_arm64") VALUES (1,'VSCode','winget install -e --id Microsoft.VisualStudioCode','brew install --cask visual-studio-code','sudo snap install code --classic','ManualInstallation'),
 (2,'Docker','winget install -e --id Docker.DockerDesktop','brew install --cask docker','sudo snap install docker','sudo snap install docker'),
 (3,'Git','winget install --id Git.Git -e --source winget','brew install --cask git','ManualInstallation','ManualInstallation'),
 (4,'JetBrains WebStorm','winget install -e --id JetBrains.WebStorm','brew install --cask webstorm','sudo snap install webstorm --classic','sudo snap install webstorm --classic'),
 (5,'Postman','winget install -e --id Postman.Postman','brew install --cask postman','sudo snap install postman','sudo snap install postman'),
 (6,'JetBrains RubyMine','winget install -e --id JetBrains.RubyMine','brew install --cask rubymine','sudo snap install postman','sudo snap install postman'),
 (7,'JetBrains CLion','winget install -e --id JetBrains.CLion','brew install --cask clion','sudo snap install clion --classic','sudo snap install clion --classic'),
 (8,'JetBrains DataGrip','winget install -e --id JetBrains.DataGrip','brew install --cask datagrip','sudo snap install datagrip --classic','sudo snap install datagrip --classic'),
 (9,'JetBrains DataSpell','winget install -e --id JetBrains.DataSpell','brew install --cask dataspell','sudo snap install dataspell --classic','sudo snap install dataspell --classic'),
 (10,'Eclipse IDE','ManualInstallation','brew install --cask eclipse-ide','sudo snap install eclipse --classic','sudo snap install eclipse --classic'),
 (11,'JetBrains GoLand','winget install -e --id JetBrains.GoLand','brew install --cask goland','sudo snap install goland --classic','sudo snap install goland --classic'),
 (12,'JetBrains IntelliJ IDEA Community','winget install -e --id JetBrains.IntelliJIDEA.Community','brew install --cask intellij-idea-ce','sudo snap install intellij-idea-community --classic','sudo snap install intellij-idea-community --classic'),
 (13,'JetBrains IntelliJ IDEA Ultimate','winget install -e --id JetBrains.IntelliJIDEA.Ultimate','brew install --cask intellij-idea','sudo snap install intellij-idea-ultimate --classic','sudo snap install intellij-idea-ultimate --classic'),
 (14,'JetBrains Rider','winget install -e --id JetBrains.Rider','brew install --cask rider','sudo snap install rider --classic','sudo snap install rider --classic'),
 (15,'JetBrains PhpStorm','winget install -e --id JetBrains.PHPStorm','brew install --cask phpstorm','sudo snap install phpstorm --classic','sudo snap install phpstorm --classic'),
 (16,'JetBrains Space','winget install -e --id JetBrains.Space','brew install --cask jetbrains-space','sudo snap install space','sudo snap install space'),
 (17,'Postgresql','winget install -e --id PostgreSQL.PostgreSQL','brew install postgresql@14','sudo snap install postgresql10','sudo snap install postgresql10'),
 (18,'PgAdmin','winget install -e --id PostgreSQL.pgAdmin','brew install --cask pgadmin4','ManualInstallation','ManualInstallation'),
 (19,'Ngrok','winget install -e --id Ngrok.Ngrok','brew install --cask ngrok','sudo snap install ngrok','sudo snap install ngrok'),
 (20,'Sublime Text','winget install -e --id SublimeHQ.SublimeText.4','brew install --cask sublime-text','sudo snap install sublime-text --classic','sudo snap install sublime-text --classic'),
 (21,'JetBrains PyCharm Community','winget install -e --id JetBrains.PyCharm.Community','brew install --cask pycharm-ce','sudo snap install pycharm-community --classic','sudo snap install pycharm-community --classic'),
 (22,'JetBrains PyCharm Proffessional','winget install -e --id JetBrains.PyCharm.Professional','brew install --cask pycharm','sudo snap install pycharm-professional --classic','sudo snap install pycharm-professional --classic'),
 (23,'Discord','winget install -e --id Discord.Discord','brew install --cask discord','sudo snap install discord','sudo snap install discord'),
 (24,'Telegram','winget install -e --id Telegram.TelegramDesktop','brew install --cask telegram','sudo snap install telegram-desktop','sudo snap install telegram-desktop'),
 (25,'NodeJS','winget install -e --id OpenJS.NodeJS','brew install node','sudo snap install node --classic','sudo snap install node --classic'),
 (26,'Go','winget install -e --id GoLang.Go.1.18','brew install go','sudo snap install go --classic','sudo snap install go --classic'),
 (27,'JDK 18','winget install -e --id Oracle.JDK.18','brew install openjdk@18','sudo snap install openjdk@18','sudo snap install openjdk@18'),
 (28,'JDK 19','winget install -e --id Oracle.JDK.19','brew install openjdk@19','sudo snap install openjdk@19','sudo snap install openjdk@19'),
 (29,'Visual Studio Community','winget install -e --id Microsoft.VisualStudio.2022.Community.Preview','Not Found','Not Found','Not Found'),
 (30,'Visual Studio Proffessional','winget install -e --id Microsoft.VisualStudio.2022.Professional.Preview','Not Found','Not Found','Not Found'),
 (31,'Visual Studio','Not Found','brew install --cask visual-studio','Not Found','Not Found'),
 (32,'Rust','winget install -e --id Rustlang.Rust.MSVC','brew install rust','sudo snap install rustup --classic','sudo snap install rustup --classic'),
 (33,'Ruby','winget install -e --id RubyInstallerTeam.Ruby.3.1','brew install ruby','sudo snap install ruby --classic','sudo snap install ruby --classic'),
 (34,'.Net Framework','winget install -e --id Microsoft.DotNet.Framework.DeveloperPack_4','brew install dotnet','sudo snap install dotnet-sdk --classic','sudo snap install dotnet-sdk --classic'),
 (35,'Python 3.9','winget install -e --id Python.Python.3.9','brew install python@3.9','ManualInstallation','ManualInstallation'),
 (36,'Python 3.10','winget install -e --id Python.Python.3.10','brew install python@3.10','ManualInstallation','ManualInstallation'),
 (37,'Python 3.11','winget install -e --id Python.Python.3.11','brew install python@3.11','ManualInstallation','ManualInstallation'),
 (38,'Vim','winget install -e --id vim.vim','brew install vim','sudo snap install vim-editor --beta','sudo snap install vim-editor --beta'),
 (39,'NeoVim','winget install -e --id Neovim.Neovim','brew install neovim','sudo snap install nvim --classic','sudo snap install nvim --classic'),
 (40,'vcpkg','ManualInstallation','brew install vcpkg','ManualInstallation','ManualInstallation'),
 (41,'Kotlin','ManualInstallation','brew install kotlin','sudo snap install kotlin --classic','sudo snap install kotlin --classic'),
 (42,'PHP','ManualInstallation','brew install php','ManualInstallation','ManualInstallation'),
 (43,'CMake','winget install -e --id Kitware.CMake','brew install cmake','sudo snap install cmake --classic','sudo snap install cmake --classic'),
 (44,'Make','ManualInstallation','brew install make','ManualInstallation','ManualInstallation'),
 (45,'Conan Package Manager','winget install -e --id JFrog.Conan','brew install conan','ManualInstallation','ManualInstallation'),
 (46,'Android Studio','winget install -e --id Google.AndroidStudio','brew install --cask android-studio','sudo snap install android-studio --classic','sudo snap install android-studio --classic'),
 (47,'MySQL','winget install -e --id Oracle.MySQL','brew install mysql','sudo snap install mysql --beta','sudo snap install mysql --beta'),
 (48,'SQLite','winget install -e --id SQLite.SQLite','brew install sqlite','ManualInstallation','ManualInstallation'),
 (49,'SQLiteBrowser','winget install -e --id DBBrowserForSQLite.DBBrowserForSQLite','brew install --cask db-browser-for-sqlite','sudo snap install sqlitebrowser','sudo snap install sqlitebrowser'),
 (50,'GNU Emacs','winget install -e --id GNU.Emacs','brew install emacs','sudo snap install emacs --classic','sudo snap install emacs --classic'),
 (51,'Nginx','ManualInstallation','brew install nginx','ManualInstallation','ManualInstallation'),
 (52,'Wget','ManualInstallation','brew install wget','ManualInstallation','ManualInstallation'),
 (53,'MSYS2','winget install -e --id MSYS2.MSYS2','Not Found','Not Found','Not Found'),
 (54,'g++','Not Found','brew install gcc','ManualInstallation','ManualInstallation'),
 (55,'gcc','Not Found','brew install gcc','ManualInstallation','ManualInstallation'),
 (56,'Nuget','winget install -e --id Microsoft.NuGet','brew install nuget','Not Found','Not Found'),
 (57,'GitHub Desktop','winget install -e --id GitHub.GitHubDesktop','brew install --cask github','sudo snap install github-gui','sudo snap install github-gui'),
 (58,'GitHub CLI','winget install -e --id GitHub.cli','brew install gh','sudo snap install gh','sudo snap install gh'),
 (59,'Kubernetes','winget install -e --id Kubernetes.kubectl','brew install kubernetes-cli','sudo snap install kubectl --classic','sudo snap install kubectl --classic'),
 (60,'Slack','winget install -e --id SlackTechnologies.Slack','brew install --cask slack','sudo snap install slack','sudo snap install slack'),
 (61,'Wordpress','winget install -e --id Automattic.Wordpress','brew install --cask wordpresscom','sudo snap install wordpress-desktop','sudo snap install wordpress-desktop'),
 (62,'Redis','ManualInstallation','brew install redis','sudo snap install redis','sudo snap install redis'),
 (63,'Code::Blocks','winget install -e --id Codeblocks.Codeblocks','ManualInstallation','ManualInstallation','ManualInstallation'),
 (64,'Google Chrome','winget install -e --id Google.Chrome','brew install --cask google-chrome','ManualInstallation','sudo snap install chromium'),
 (65,'Mozilla Firefox','winget install -e --id Mozilla.Firefox','brew install --cask firefox','sudo snap install firefox','sudo snap install firefox'),
 (66,'Opera','winget install -e --id Opera.Opera','brew install --cask opera','sudo snap install opera','sudo snap install opera'),
 (67,'MSBuild Tools','winget install Microsoft.VisualStudio.2022.BuildTools','Not Found','Not Found','Not Found');
INSERT INTO "CDevelopmentTools" ("id","Name","Windows","macOS","Linux_amd64","Linux_arm64") VALUES (1,'VSCode','winget install -e --id Microsoft.VisualStudioCode','brew install --cask visual-studio-code','sudo snap install code --classic','ManualInstallation'),
 (2,'Docker','winget install -e --id Docker.DockerDesktop','brew install --cask docker','sudo snap install docker','sudo snap install docker'),
 (3,'Git','winget install --id Git.Git -e --source winget','brew install --cask git','ManualInstallation','ManualInstallation'),
 (4,'Sublime Text','winget install -e --id SublimeHQ.SublimeText.4','brew install --cask sublime-text','sudo snap install sublime-text --classic','sudo snap install sublime-text --classic'),
 (5,'Visual Studio Community','winget install -e --id Microsoft.VisualStudio.2022.Community.Preview','Not Found','Not Found','Not Found'),
 (6,'Visual Studio Proffessional','winget install -e --id Microsoft.VisualStudio.2022.Professional.Preview','Not Found','Not Found','Not Found'),
 (7,'JetBrains CLion','winget install -e --id JetBrains.CLion','brew install --cask clion','sudo snap install clion --classic','sudo snap install clion --classic'),
 (8,'vcpkg','ManualInstallation','brew install vcpkg','ManualInstallation','ManualInstallation'),
 (9,'JetBrains Space','winget install -e --id JetBrains.Space','brew install --cask jetbrains-space','sudo snap install space','sudo snap install space'),
 (10,'Postgresql','winget install -e --id PostgreSQL.PostgreSQL','brew install postgresql@14','sudo snap install postgresql10','sudo snap install postgresql10'),
 (11,'PgAdmin','winget install -e --id PostgreSQL.pgAdmin','brew install --cask pgadmin4','ManualInstallation','ManualInstallation'),
 (12,'Vim','winget install -e --id vim.vim','winget install -e --id vim.vim','sudo snap install vim-editor --beta','sudo snap install vim-editor --beta'),
 (13,'NeoVim','winget install -e --id Neovim.Neovim','brew install neovim','sudo snap install nvim --classic','sudo snap install nvim --classic'),
 (14,'Visual Studio','Not Found','brew install --cask visual-studio','Not Found','Not Found'),
 (15,'JetBrains DataGrip','winget install -e --id JetBrains.DataGrip','brew install --cask datagrip','sudo snap install datagrip --classic','sudo snap install datagrip --classic'),
 (16,'JetBrains DataSpell','winget install -e --id JetBrains.DataSpell','brew install --cask dataspell','sudo snap install dataspell --classic','sudo snap install dataspell --classic'),
 (17,'CMake','winget install -e --id Kitware.CMake','brew install cmake','sudo snap install cmake --classic','sudo snap install cmake --classic'),
 (18,'Make','ManualInstallation','brew install make','ManualInstallation','ManualInstallation'),
 (19,'Conan Package Manager','winget install -e --id JFrog.Conan','brew install conan','ManualInstallation','ManualInstallation'),
 (20,'Wget','ManualInstallation','brew install wget','ManualInstallation','ManualInstallation'),
 (21,'MySQL','winget install -e --id Oracle.MySQL','brew install mysql','sudo snap install mysql --beta','sudo snap install mysql --beta'),
 (22,'SQLite','winget install -e --id SQLite.SQLite','brew install sqlite','ManualInstallation','ManualInstallation'),
 (23,'SQLiteBrowser','winget install -e --id DBBrowserForSQLite.DBBrowserForSQLite','brew install --cask db-browser-for-sqlite','sudo snap install sqlitebrowser','sudo snap install sqlitebrowser'),
 (24,'GNU Emacs','winget install -e --id GNU.Emacs','brew install emacs','sudo snap install emacs --classic','sudo snap install emacs --classic'),
 (25,'MSYS2','winget install -e --id MSYS2.MSYS2','ManualInstallation','ManualInstallation','ManualInstallation'),
 (26,'g++','Not Found','brew install gcc','ManualInstallation','ManualInstallation'),
 (27,'gcc','Not Found','brew install gcc','ManualInstallation','ManualInstallation'),
 (28,'GitHub Desktop','winget install -e --id GitHub.GitHubDesktop','brew install --cask github','sudo snap install github-gui','sudo snap install github-gui'),
 (29,'GitHub CLI','winget install -e --id GitHub.cli','brew install gh','sudo snap install gh','sudo snap install gh'),
 (30,'Kubernetes','winget install -e --id Kubernetes.kubectl','brew install kubernetes-cli','sudo snap install kubectl --classic','sudo snap install kubectl --classic'),
 (31,'Slack','winget install -e --id SlackTechnologies.Slack','brew install --cask slack','sudo snap install slack','sudo snap install slack'),
 (32,'AllPackages','AllPackages','AllPackages','AllPackages','AllPackages'),
 (33,'MSBuild Tools','winget install Microsoft.VisualStudio.2022.BuildTools','Not Found','Not Found','Not Found');
INSERT INTO "CSDevelopmentTools" ("id","Name","Windows","macOS","Linux_amd64","Linux_arm64") VALUES (1,'VSCode','winget install -e --id Microsoft.VisualStudioCode','brew install --cask visual-studio-code','sudo snap install code --classic','ManualInstallation'),
 (2,'Docker','winget install -e --id Docker.DockerDesktop','brew install --cask docker','sudo snap install docker','sudo snap install docker'),
 (3,'Git','winget install --id Git.Git -e --source winget','brew install --cask git','ManualInstallation','ManualInstallation'),
 (4,'Sublime Text','winget install -e --id SublimeHQ.SublimeText.4','brew install --cask sublime-text','sudo snap install sublime-text --classic','sudo snap install sublime-text --classic'),
 (5,'Visual Studio Community','winget install -e --id Microsoft.VisualStudio.2022.Community.Preview','Not Found','Not Found','Not Found'),
 (6,'Visual Studio Proffessional','winget install -e --id Microsoft.VisualStudio.2022.Professional.Preview','Not Found','Not Found','Not Found'),
 (7,'JetBrains Rider','winget install -e --id JetBrains.Rider','brew install --cask rider','sudo snap install rider --classic','sudo snap install rider --classic'),
 (8,'.Net Framework','winget install -e --id Microsoft.DotNet.Framework.DeveloperPack_4','brew install dotnet','sudo snap install dotnet-sdk --classic','sudo snap install dotnet-sdk --classic'),
 (9,'Postman','winget install -e --id Postman.Postman','brew install --cask postman','sudo snap install postman','sudo snap install postman'),
 (10,'JetBrains Space','winget install -e --id JetBrains.Space','brew install --cask jetbrains-space','sudo snap install space','sudo snap install space'),
 (11,'Postgresql','winget install -e --id PostgreSQL.PostgreSQL','brew install postgresql@14','sudo snap install postgresql10','sudo snap install postgresql10'),
 (12,'PgAdmin','winget install -e --id PostgreSQL.pgAdmin','brew install --cask pgadmin4','winget install -e --id PostgreSQL.pgAdmin','winget install -e --id PostgreSQL.pgAdmin'),
 (13,'Vim','winget install -e --id vim.vim','winget install -e --id vim.vim','sudo snap install vim-editor --beta','sudo snap install vim-editor --beta'),
 (14,'NeoVim','winget install -e --id Neovim.Neovim','brew install neovim','sudo snap install nvim --classic','sudo snap install nvim --classic'),
 (15,'Ngrok','winget install -e --id Ngrok.Ngrok','brew install --cask ngrok','sudo snap install ngrok','sudo snap install ngrok'),
 (16,'Visual Studio','Not Found','brew install --cask visual-studio','Not Found','Not Found'),
 (17,'Wget','ManualInstallation','brew install wget','ManualInstallation','ManualInstallation'),
 (18,'MySQL','winget install -e --id Oracle.MySQL','brew install mysql','sudo snap install mysql --beta','sudo snap install mysql --beta'),
 (19,'SQLite','winget install -e --id SQLite.SQLite','brew install sqlite','ManualInstallation','ManualInstallation'),
 (20,'SQLiteBrowser','winget install -e --id DBBrowserForSQLite.DBBrowserForSQLite','brew install --cask db-browser-for-sqlite','sudo snap install sqlitebrowser','sudo snap install sqlitebrowser'),
 (21,'GNU Emacs','winget install -e --id GNU.Emacs','brew install emacs','sudo snap install emacs --classic','sudo snap install emacs --classic'),
 (22,'Nginx','ManualInstallation','brew install nginx','ManualInstallation','ManualInstallation'),
 (23,'Nuget','winget install -e --id Microsoft.NuGet','brew install nuget','Not Found','Not Found'),
 (24,'GitHub Desktop','winget install -e --id GitHub.GitHubDesktop','brew install --cask github','sudo snap install github-gui','sudo snap install github-gui'),
 (25,'GitHub CLI','winget install -e --id GitHub.cli','brew install gh','sudo snap install gh','sudo snap install gh'),
 (26,'Kubernetes','winget install -e --id Kubernetes.kubectl','brew install kubernetes-cli','sudo snap install kubectl --classic','sudo snap install kubectl --classic'),
 (27,'Slack','winget install -e --id SlackTechnologies.Slack','brew install --cask slack','sudo snap install slack','sudo snap install slack'),
 (28,'AllPackages','AllPackages','AllPackages','AllPackages','AllPackages'),
 (29,'MSBuild Tools','winget install Microsoft.VisualStudio.2022.BuildTools','Not Found','Not Found','Not Found');
INSERT INTO "CppDevelopmentTools" ("id","Name","Windows","macOS","Linux_amd64","Linux_arm64") VALUES (1,'VSCode','winget install -e --id Microsoft.VisualStudioCode','brew install --cask visual-studio-code','sudo snap install code --classic','ManualInstallation'),
 (2,'Docker','winget install -e --id Docker.DockerDesktop','brew install --cask docker','sudo snap install docker','sudo snap install docker'),
 (3,'Git','winget install --id Git.Git -e --source winget','brew install --cask git','ManualInstallation','ManualInstallation'),
 (4,'Sublime Text','winget install -e --id SublimeHQ.SublimeText.4','brew install --cask sublime-text','sudo snap install sublime-text --classic','sudo snap install sublime-text --classic'),
 (5,'Visual Studio Community','winget install -e --id Microsoft.VisualStudio.2022.Community.Preview','Not Found','Not Found','Not Found'),
 (6,'Visual Studio Proffessional','winget install -e --id Microsoft.VisualStudio.2022.Professional.Preview','Not Found','Not Found','Not Found'),
 (7,'JetBrains CLion','winget install -e --id JetBrains.CLion','brew install --cask clion','sudo snap install clion --classic','sudo snap install clion --classic'),
 (8,'vcpkg','ManualInstallation','brew install vcpkg','ManualInstallation','ManualInstallation'),
 (9,'Postman','winget install -e --id Postman.Postman','brew install --cask postman','sudo snap install postman','sudo snap install postman'),
 (10,'JetBrains Space','winget install -e --id JetBrains.Space','brew install --cask jetbrains-space','sudo snap install space','sudo snap install space'),
 (11,'Postgresql','winget install -e --id PostgreSQL.PostgreSQL','brew install postgresql@14','sudo snap install postgresql10','sudo snap install postgresql10'),
 (12,'PgAdmin','winget install -e --id PostgreSQL.pgAdmin','brew install --cask pgadmin4','ManualInstallation','ManualInstallation'),
 (13,'Vim','winget install -e --id vim.vim','winget install -e --id vim.vim','sudo snap install vim-editor --beta','sudo snap install vim-editor --beta'),
 (14,'NeoVim','winget install -e --id Neovim.Neovim','brew install neovim','sudo snap install nvim --classic','sudo snap install nvim --classic'),
 (15,'Ngrok','winget install -e --id Ngrok.Ngrok','brew install --cask ngrok','sudo snap install ngrok','sudo snap install ngrok'),
 (16,'Visual Studio','Not Found','brew install --cask visual-studio','Not Found','Not Found'),
 (17,'JetBrains DataGrip','winget install -e --id JetBrains.DataGrip','brew install --cask datagrip','sudo snap install datagrip --classic','sudo snap install datagrip --classic'),
 (18,'JetBrains DataSpell','winget install -e --id JetBrains.DataSpell','brew install --cask dataspell','sudo snap install dataspell --classic','sudo snap install dataspell --classic'),
 (19,'CMake','winget install -e --id Kitware.CMake','brew install cmake','sudo snap install cmake --classic','sudo snap install cmake --classic'),
 (20,'Make','ManualInstallation','brew install make','ManualInstallation','ManualInstallation'),
 (21,'Conan Package Manager','winget install -e --id JFrog.Conan','brew install conan','ManualInstallation','ManualInstallation'),
 (22,'Wget','ManualInstallation','brew install wget','ManualInstallation','ManualInstallation'),
 (23,'MySQL','winget install -e --id Oracle.MySQL','brew install mysql','sudo snap install mysql --beta','sudo snap install mysql --beta'),
 (24,'SQLite','winget install -e --id SQLite.SQLite','brew install sqlite','ManualInstallation','ManualInstallation'),
 (25,'SQLiteBrowser','winget install -e --id DBBrowserForSQLite.DBBrowserForSQLite','brew install --cask db-browser-for-sqlite','sudo snap install sqlitebrowser','sudo snap install sqlitebrowser'),
 (26,'GNU Emacs','winget install -e --id GNU.Emacs','brew install emacs','sudo snap install emacs --classic','sudo snap install emacs --classic'),
 (27,'Nginx','ManualInstallation','brew install nginx','ManualInstallation','ManualInstallation'),
 (28,'MSYS2','winget install -e --id MSYS2.MSYS2','ManualInstallation','ManualInstallation','ManualInstallation'),
 (29,'g++','Not Found','brew install gcc','ManualInstallation','ManualInstallation'),
 (30,'gcc','Not Found','brew install gcc','ManualInstallation','ManualInstallation'),
 (31,'GitHub Desktop','winget install -e --id GitHub.GitHubDesktop','brew install --cask github','sudo snap install github-gui','sudo snap install github-gui'),
 (32,'GitHub CLI','winget install -e --id GitHub.cli','brew install gh','sudo snap install gh','sudo snap install gh'),
 (33,'Kubernetes','winget install -e --id Kubernetes.kubectl','brew install kubernetes-cli','sudo snap install kubectl --classic','sudo snap install kubectl --classic'),
 (34,'Slack','winget install -e --id SlackTechnologies.Slack','brew install --cask slack','sudo snap install slack','sudo snap install slack'),
 (35,'AllPackages','AllPackages','AllPackages','AllPackages','AllPackages'),
 (36,'MSBuild Tools','winget install Microsoft.VisualStudio.2022.BuildTools','Not Found','Not Found','Not Found');
INSERT INTO "GoDevelopmentTools" ("id","Name","Windows","macOS","Linux_amd64","Linux_arm64") VALUES (1,'VSCode','winget install -e --id Microsoft.VisualStudioCode','brew install --cask visual-studio-code','sudo snap install code --classic','ManualInstallation'),
 (2,'Docker','winget install -e --id Docker.DockerDesktop','brew install --cask docker','sudo snap install docker','sudo snap install docker'),
 (3,'Git','winget install --id Git.Git -e --source winget','brew install --cask git','ManualInstallation','ManualInstallation'),
 (4,'Sublime Text','winget install -e --id SublimeHQ.SublimeText.4','brew install --cask sublime-text','sudo snap install sublime-text --classic','sudo snap install sublime-text --classic'),
 (5,'Visual Studio Community','winget install -e --id Microsoft.VisualStudio.2022.Community.Preview','Not Found','Not Found','Not Found'),
 (6,'Visual Studio Proffessional','winget install -e --id Microsoft.VisualStudio.2022.Professional.Preview','Not Found','Not Found','Not Found'),
 (7,'JetBrains GoLand','winget install -e --id JetBrains.GoLand','brew install --cask goland','sudo snap install goland --classic','sudo snap install goland --classic'),
 (8,'Go','winget install -e --id GoLang.Go.1.18','brew install go','sudo snap install go --classic','sudo snap install go --classic'),
 (9,'Postman','winget install -e --id Postman.Postman','brew install --cask postman','sudo snap install postman','sudo snap install postman'),
 (10,'JetBrains Space','winget install -e --id JetBrains.Space','brew install --cask jetbrains-space','sudo snap install space','sudo snap install space'),
 (11,'Postgresql','winget install -e --id PostgreSQL.PostgreSQL','brew install postgresql@14','sudo snap install postgresql10','sudo snap install postgresql10'),
 (12,'PgAdmin','winget install -e --id PostgreSQL.pgAdmin','brew install --cask pgadmin4','ManualInstallation','ManualInstallation'),
 (13,'Vim','winget install -e --id vim.vim','winget install -e --id vim.vim','sudo snap install vim-editor --beta','sudo snap install vim-editor --beta'),
 (14,'NeoVim','winget install -e --id Neovim.Neovim','brew install neovim','sudo snap install nvim --classic','sudo snap install nvim --classic'),
 (15,'Ngrok','winget install -e --id Ngrok.Ngrok','brew install --cask ngrok','sudo snap install ngrok','sudo snap install ngrok'),
 (16,'Visual Studio','Not Found','brew install --cask visual-studio','Not Found','Not Found'),
 (17,'JetBrains DataGrip','winget install -e --id JetBrains.DataGrip','brew install --cask datagrip','sudo snap install datagrip --classic','sudo snap install datagrip --classic'),
 (18,'JetBrains DataSpell','winget install -e --id JetBrains.DataSpell','brew install --cask dataspell','sudo snap install dataspell --classic','sudo snap install dataspell --classic'),
 (19,'Wget','ManualInstallation','brew install wget','ManualInstallation','ManualInstallation'),
 (20,'MySQL','winget install -e --id Oracle.MySQL','brew install mysql','sudo snap install mysql --beta','sudo snap install mysql --beta'),
 (21,'SQLite','winget install -e --id SQLite.SQLite','brew install sqlite','ManualInstallation','ManualInstallation'),
 (22,'SQLiteBrowser','winget install -e --id DBBrowserForSQLite.DBBrowserForSQLite','brew install --cask db-browser-for-sqlite','sudo snap install sqlitebrowser','sudo snap install sqlitebrowser'),
 (23,'GNU Emacs','winget install -e --id GNU.Emacs','brew install emacs','sudo snap install emacs --classic','sudo snap install emacs --classic'),
 (24,'Nginx','ManualInstallation','brew install nginx','ManualInstallation','ManualInstallation'),
 (25,'GitHub Desktop','winget install -e --id GitHub.GitHubDesktop','brew install --cask github','sudo snap install github-gui','sudo snap install github-gui'),
 (26,'GitHub CLI','winget install -e --id GitHub.cli','brew install gh','sudo snap install gh','sudo snap install gh'),
 (27,'Kubernetes','winget install -e --id Kubernetes.kubectl','brew install kubernetes-cli','sudo snap install kubectl --classic','sudo snap install kubectl --classic'),
 (28,'Slack','winget install -e --id SlackTechnologies.Slack','brew install --cask slack','sudo snap install slack','sudo snap install slack'),
 (29,'AllPackages','AllPackages','AllPackages','AllPackages','AllPackages');
INSERT INTO "JavaDevelopmentTools" ("id","Name","Windows","macOS","Linux_amd64","Linux_arm64") VALUES (1,'VSCode','winget install -e --id Microsoft.VisualStudioCode','brew install --cask visual-studio-code','sudo snap install code --classic','ManualInstallation'),
 (2,'Docker','winget install -e --id Docker.DockerDesktop','brew install --cask docker','sudo snap install docker','sudo snap install docker'),
 (3,'Git','winget install --id Git.Git -e --source winget','brew install --cask git','ManualInstallation','ManualInstallation'),
 (4,'Sublime Text','winget install -e --id SublimeHQ.SublimeText.4','brew install --cask sublime-text','sudo snap install sublime-text --classic','sudo snap install sublime-text --classic'),
 (5,'Visual Studio Community','winget install -e --id Microsoft.VisualStudio.2022.Community.Preview','Not Found','Not Found','Not Found'),
 (6,'Visual Studio Proffessional','winget install -e --id Microsoft.VisualStudio.2022.Professional.Preview','Not Found','Not Found','Not Found'),
 (7,'JDK 18','winget install -e --id Oracle.JDK.18','brew install openjdk@18','sudo snap install openjdk@18','sudo snap install openjdk@18'),
 (8,'JDK 19','winget install -e --id Oracle.JDK.19','brew install openjdk@19','sudo snap install openjdk@19','sudo snap install openjdk@19'),
 (9,'Eclipse IDE','ManualInstallation','brew install --cask eclipse-ide','sudo snap install eclipse --classic','sudo snap install eclipse --classic'),
 (10,'Postman','winget install -e --id Postman.Postman','brew install --cask postman','sudo snap install postman','sudo snap install postman'),
 (11,'JetBrains Space','winget install -e --id JetBrains.Space','brew install --cask jetbrains-space','sudo snap install space','sudo snap install space'),
 (12,'Postgresql','winget install -e --id PostgreSQL.PostgreSQL','brew install postgresql@14','sudo snap install postgresql10','sudo snap install postgresql10'),
 (13,'PgAdmin','winget install -e --id PostgreSQL.pgAdmin','brew install --cask pgadmin4','ManualInstallation','ManualInstallation'),
 (14,'Vim','winget install -e --id vim.vim','winget install -e --id vim.vim','sudo snap install vim-editor --beta','sudo snap install vim-editor --beta'),
 (15,'NeoVim','winget install -e --id Neovim.Neovim','brew install neovim','sudo snap install nvim --classic','sudo snap install nvim --classic'),
 (16,'Ngrok','winget install -e --id Ngrok.Ngrok','brew install --cask ngrok','sudo snap install ngrok','sudo snap install ngrok'),
 (17,'Visual Studio','Not Found','brew install --cask visual-studio','Not Found','Not Found'),
 (18,'JetBrains DataGrip','winget install -e --id JetBrains.DataGrip','brew install --cask datagrip','sudo snap install datagrip --classic','sudo snap install datagrip --classic'),
 (19,'JetBrains DataSpell','winget install -e --id JetBrains.DataSpell','brew install --cask dataspell','sudo snap install dataspell --classic','sudo snap install dataspell --classic'),
 (20,'Wget','ManualInstallation','brew install wget','ManualInstallation','ManualInstallation'),
 (21,'Android Studio','winget install -e --id Google.AndroidStudio','brew install --cask android-studio','sudo snap install android-studio --classic','sudo snap install android-studio --classic'),
 (22,'MySQL','winget install -e --id Oracle.MySQL','brew install mysql','sudo snap install mysql --beta','sudo snap install mysql --beta'),
 (23,'SQLite','winget install -e --id SQLite.SQLite','brew install sqlite','ManualInstallation','ManualInstallation'),
 (24,'SQLiteBrowser','winget install -e --id DBBrowserForSQLite.DBBrowserForSQLite','brew install --cask db-browser-for-sqlite','sudo snap install sqlitebrowser','sudo snap install sqlitebrowser'),
 (25,'GNU Emacs','winget install -e --id GNU.Emacs','brew install emacs','sudo snap install emacs --classic','sudo snap install emacs --classic'),
 (26,'Nginx','ManualInstallation','brew install nginx','ManualInstallation','ManualInstallation'),
 (27,'GitHub Desktop','winget install -e --id GitHub.GitHubDesktop','brew install --cask github','sudo snap install github-gui','sudo snap install github-gui'),
 (28,'GitHub CLI','winget install -e --id GitHub.cli','brew install gh','sudo snap install gh','sudo snap install gh'),
 (29,'Kubernetes','winget install -e --id Kubernetes.kubectl','brew install kubernetes-cli','sudo snap install kubectl --classic','sudo snap install kubectl --classic'),
 (30,'Slack','winget install -e --id SlackTechnologies.Slack','brew install --cask slack','sudo snap install slack','sudo snap install slack'),
 (31,'AllPackages','AllPackages','AllPackages','AllPackages','AllPackages'),
 (32,'MSBuild Tools','winget install Microsoft.VisualStudio.2022.BuildTools','Not Found','Not Found','Not Found');
INSERT INTO "JavaScriptDevelopmentTools" ("id","Name","Windows","macOS","Linux_amd64","Linux_arm64") VALUES (1,'VSCode','winget install -e --id Microsoft.VisualStudioCode','brew install --cask visual-studio-code','sudo snap install code --classic','ManualInstallation'),
 (2,'Docker','winget install -e --id Docker.DockerDesktop','brew install --cask docker','sudo snap install docker','sudo snap install docker'),
 (3,'Git','winget install --id Git.Git -e --source winget','brew install --cask git','ManualInstallation','ManualInstallation'),
 (4,'Sublime Text','winget install -e --id SublimeHQ.SublimeText.4','brew install --cask sublime-text','sudo snap install sublime-text --classic','sudo snap install sublime-text --classic'),
 (5,'Visual Studio Community','winget install -e --id Microsoft.VisualStudio.2022.Community.Preview','Not Found','Not Found','Not Found'),
 (6,'Visual Studio Proffessional','winget install -e --id Microsoft.VisualStudio.2022.Professional.Preview','Not Found','Not Found','Not Found'),
 (7,'JetBrains WebStorm','winget install -e --id JetBrains.WebStorm','brew install --cask webstorm','sudo snap install webstorm --classic','sudo snap install webstorm --classic'),
 (8,'NodeJS','winget install -e --id OpenJS.NodeJS','brew install node','sudo snap install node --classic','sudo snap install node --classic'),
 (9,'Postman','winget install -e --id Postman.Postman','brew install --cask postman','sudo snap install postman','sudo snap install postman'),
 (10,'JetBrains Space','winget install -e --id JetBrains.Space','brew install --cask jetbrains-space','sudo snap install space','sudo snap install space'),
 (11,'Postgresql','winget install -e --id PostgreSQL.PostgreSQL','brew install postgresql@14','sudo snap install postgresql10','sudo snap install postgresql10'),
 (12,'PgAdmin','winget install -e --id PostgreSQL.pgAdmin','brew install --cask pgadmin4','ManualInstallation','ManualInstallation'),
 (13,'Vim','winget install -e --id vim.vim','winget install -e --id vim.vim','sudo snap install vim-editor --beta','sudo snap install vim-editor --beta'),
 (14,'NeoVim','winget install -e --id Neovim.Neovim','brew install neovim','sudo snap install nvim --classic','sudo snap install nvim --classic'),
 (15,'Ngrok','winget install -e --id Ngrok.Ngrok','brew install --cask ngrok','sudo snap install ngrok','sudo snap install ngrok'),
 (16,'Visual Studio','Not Found','brew install --cask visual-studio','Not Found','Not Found'),
 (17,'JetBrains DataGrip','winget install -e --id JetBrains.DataGrip','brew install --cask datagrip','sudo snap install datagrip --classic','sudo snap install datagrip --classic'),
 (18,'JetBrains DataSpell','winget install -e --id JetBrains.DataSpell','brew install --cask dataspell','sudo snap install dataspell --classic','sudo snap install dataspell --classic'),
 (19,'Wget','ManualInstallation','brew install wget','ManualInstallation','ManualInstallation'),
 (20,'MySQL','winget install -e --id Oracle.MySQL','brew install mysql','sudo snap install mysql --beta','sudo snap install mysql --beta'),
 (21,'SQLite','winget install -e --id SQLite.SQLite','brew install sqlite','ManualInstallation','ManualInstallation'),
 (22,'SQLiteBrowser','winget install -e --id DBBrowserForSQLite.DBBrowserForSQLite','brew install --cask db-browser-for-sqlite','sudo snap install sqlitebrowser','sudo snap install sqlitebrowser'),
 (23,'GNU Emacs','winget install -e --id GNU.Emacs','brew install emacs','sudo snap install emacs --classic','sudo snap install emacs --classic'),
 (24,'Nginx','ManualInstallation','brew install nginx','ManualInstallation','ManualInstallation'),
 (25,'GitHub Desktop','winget install -e --id GitHub.GitHubDesktop','brew install --cask github','sudo snap install github-gui','sudo snap install github-gui'),
 (26,'GitHub CLI','winget install -e --id GitHub.cli','brew install gh','sudo snap install gh','sudo snap install gh'),
 (27,'Kubernetes','winget install -e --id Kubernetes.kubectl','brew install kubernetes-cli','sudo snap install kubectl --classic','sudo snap install kubectl --classic'),
 (28,'Slack','winget install -e --id SlackTechnologies.Slack','brew install --cask slack','sudo snap install slack','sudo snap install slack'),
 (29,'Wordpress','winget install -e --id Automattic.Wordpress','brew install --cask wordpresscom','sudo snap install wordpress-desktop','sudo snap install wordpress-desktop'),
 (30,'Redis','ManualInstallation','brew install redis','sudo snap install redis','sudo snap install redis'),
 (31,'AllPackages','AllPackages','AllPackages','AllPackages','AllPackages'),
 (32,'MSBuild Tools','winget install Microsoft.VisualStudio.2022.BuildTools','Not Found','Not Found','Not Found');
INSERT INTO "KotlinDevelopmentTools" ("id","Name","Windows","macOS","Linux_amd64","Linux_arm64") VALUES (1,'VSCode','winget install -e --id Microsoft.VisualStudioCode','brew install --cask visual-studio-code','sudo snap install code --classic','ManualInstallation'),
 (2,'Docker','winget install -e --id Docker.DockerDesktop','brew install --cask docker','sudo snap install docker','sudo snap install docker'),
 (3,'Git','winget install --id Git.Git -e --source winget','brew install --cask git','ManualInstallation','ManualInstallation'),
 (4,'Sublime Text','winget install -e --id SublimeHQ.SublimeText.4','brew install --cask sublime-text','sudo snap install sublime-text --classic','sudo snap install sublime-text --classic'),
 (5,'Visual Studio Community','winget install -e --id Microsoft.VisualStudio.2022.Community.Preview','Not Found','Not Found','Not Found'),
 (6,'Visual Studio Proffessional','winget install -e --id Microsoft.VisualStudio.2022.Professional.Preview','Not Found','Not Found','Not Found'),
 (7,'Eclipse IDE','ManualInstallation','brew install --cask eclipse-ide','sudo snap install eclipse --classic','sudo snap install eclipse --classic'),
 (8,'Kotlin','ManualInstallation','brew install kotlin','sudo snap install kotlin --classic','sudo snap install kotlin --classic'),
 (9,'JetBrains Space','winget install -e --id JetBrains.Space','brew install --cask jetbrains-space','sudo snap install space','sudo snap install space'),
 (10,'Postgresql','winget install -e --id PostgreSQL.PostgreSQL','brew install postgresql@14','sudo snap install postgresql10','sudo snap install postgresql10'),
 (11,'PgAdmin','winget install -e --id PostgreSQL.pgAdmin','brew install --cask pgadmin4','ManualInstallation','ManualInstallation'),
 (12,'Vim','winget install -e --id vim.vim','winget install -e --id vim.vim','sudo snap install vim-editor --beta','sudo snap install vim-editor --beta'),
 (13,'NeoVim','winget install -e --id Neovim.Neovim','brew install neovim','sudo snap install nvim --classic','sudo snap install nvim --classic'),
 (14,'Visual Studio','Not Found','brew install --cask visual-studio','Not Found','Not Found'),
 (15,'Wget','ManualInstallation','brew install wget','ManualInstallation','ManualInstallation'),
 (16,'Android Studio','winget install -e --id Google.AndroidStudio','brew install --cask android-studio','sudo snap install android-studio --classic','sudo snap install android-studio --classic'),
 (17,'MySQL','winget install -e --id Oracle.MySQL','brew install mysql','sudo snap install mysql --beta','sudo snap install mysql --beta'),
 (18,'SQLite','winget install -e --id SQLite.SQLite','brew install sqlite','ManualInstallation','ManualInstallation'),
 (19,'SQLiteBrowser','winget install -e --id DBBrowserForSQLite.DBBrowserForSQLite','brew install --cask db-browser-for-sqlite','sudo snap install sqlitebrowser','sudo snap install sqlitebrowser'),
 (20,'GNU Emacs','winget install -e --id GNU.Emacs','brew install emacs','sudo snap install emacs --classic','sudo snap install emacs --classic'),
 (21,'GitHub Desktop','winget install -e --id GitHub.GitHubDesktop','brew install --cask github','sudo snap install github-gui','sudo snap install github-gui'),
 (22,'GitHub CLI','winget install -e --id GitHub.cli','brew install gh','sudo snap install gh','sudo snap install gh'),
 (23,'Kubernetes','winget install -e --id Kubernetes.kubectl','brew install kubernetes-cli','sudo snap install kubectl --classic','sudo snap install kubectl --classic'),
 (24,'Slack','winget install -e --id SlackTechnologies.Slack','brew install --cask slack','sudo snap install slack','sudo snap install slack'),
 (25,'AllPackages','AllPackages','AllPackages','AllPackages','AllPackages');
INSERT INTO "PHPDevelopmentTools" ("id","Name","Windows","macOS","Linux_amd64","Linux_arm64") VALUES (1,'VSCode','winget install -e --id Microsoft.VisualStudioCode','brew install --cask visual-studio-code','sudo snap install code --classic','ManualInstallation'),
 (2,'Docker','winget install -e --id Docker.DockerDesktop','brew install --cask docker','sudo snap install docker','sudo snap install docker'),
 (3,'Git','winget install --id Git.Git -e --source winget','brew install --cask git','ManualInstallation','ManualInstallation'),
 (4,'Sublime Text','winget install -e --id SublimeHQ.SublimeText.4','brew install --cask sublime-text','sudo snap install sublime-text --classic','sudo snap install sublime-text --classic'),
 (5,'Visual Studio Community','winget install -e --id Microsoft.VisualStudio.2022.Community.Preview','Not Found','Not Found','Not Found'),
 (6,'Visual Studio Proffessional','winget install -e --id Microsoft.VisualStudio.2022.Professional.Preview','Not Found','Not Found','Not Found'),
 (7,'JetBrains PhpStorm','winget install -e --id JetBrains.PHPStorm','brew install --cask phpstorm','sudo snap install phpstorm --classic','sudo snap install phpstorm --classic'),
 (8,'Postman','winget install -e --id Postman.Postman','brew install --cask postman','sudo snap install postman','sudo snap install postman'),
 (9,'JetBrains Space','winget install -e --id JetBrains.Space','brew install --cask jetbrains-space','sudo snap install space','sudo snap install space'),
 (10,'Postgresql','winget install -e --id PostgreSQL.PostgreSQL','brew install postgresql@14','sudo snap install postgresql10','sudo snap install postgresql10'),
 (11,'PgAdmin','winget install -e --id PostgreSQL.pgAdmin','brew install --cask pgadmin4','ManualInstallation','ManualInstallation'),
 (12,'Vim','winget install -e --id vim.vim','winget install -e --id vim.vim','sudo snap install vim-editor --beta','sudo snap install vim-editor --beta'),
 (13,'NeoVim','winget install -e --id Neovim.Neovim','brew install neovim','sudo snap install nvim --classic','sudo snap install nvim --classic'),
 (14,'Ngrok','winget install -e --id Ngrok.Ngrok','brew install --cask ngrok','sudo snap install ngrok','sudo snap install ngrok'),
 (15,'Visual Studio','Not Found','brew install --cask visual-studio','Not Found','Not Found'),
 (16,'PHP','ManualInstallation','brew install php','ManualInstallation','ManualInstallation'),
 (17,'Wget','ManualInstallation','brew install wget','ManualInstallation','ManualInstallation'),
 (18,'MySQL','winget install -e --id Oracle.MySQL','brew install mysql','sudo snap install mysql --beta','sudo snap install mysql --beta'),
 (19,'SQLite','winget install -e --id SQLite.SQLite','brew install sqlite','ManualInstallation','ManualInstallation'),
 (20,'SQLiteBrowser','winget install -e --id DBBrowserForSQLite.DBBrowserForSQLite','brew install --cask db-browser-for-sqlite','sudo snap install sqlitebrowser','sudo snap install sqlitebrowser'),
 (21,'GNU Emacs','winget install -e --id GNU.Emacs','brew install emacs','sudo snap install emacs --classic','sudo snap install emacs --classic'),
 (22,'GitHub Desktop','winget install -e --id GitHub.GitHubDesktop','brew install --cask github','sudo snap install github-gui','sudo snap install github-gui'),
 (23,'GitHub CLI','winget install -e --id GitHub.cli','brew install gh','sudo snap install gh','sudo snap install gh'),
 (24,'Kubernetes','winget install -e --id Kubernetes.kubectl','brew install kubernetes-cli','sudo snap install kubectl --classic','sudo snap install kubectl --classic'),
 (25,'Slack','winget install -e --id SlackTechnologies.Slack','brew install --cask slack','sudo snap install slack','sudo snap install slack'),
 (26,'AllPackages','AllPackages','AllPackages','AllPackages','AllPackages');
INSERT INTO "PythonDevelopmentTools" ("id","Name","Windows","macOS","Linux_amd64","Linux_arm64") VALUES (1,'VSCode','winget install -e --id Microsoft.VisualStudioCode','brew install --cask visual-studio-code','sudo snap install code --classic','ManualInstallation'),
 (2,'Docker','winget install -e --id Docker.DockerDesktop','brew install --cask docker','sudo snap install docker','sudo snap install docker'),
 (3,'Git','winget install --id Git.Git -e --source winget','brew install --cask git','ManualInstallation','ManualInstallation'),
 (4,'Sublime Text','winget install -e --id SublimeHQ.SublimeText.4','brew install --cask sublime-text','sudo snap install sublime-text --classic','sudo snap install sublime-text --classic'),
 (5,'Python 3.9','winget install -e --id Python.Python.3.9','brew install python@3.9','ManualInstallation','ManualInstallation'),
 (6,'Python 3.10','winget install -e --id Python.Python.3.10','brew install python@3.10','ManualInstallation','ManualInstallation'),
 (7,'Python 3.11','winget install -e --id Python.Python.3.11','brew install python@3.11','ManualInstallation','ManualInstallation'),
 (8,'JetBrains PyCharm Community','winget install -e --id JetBrains.PyCharm.Community','brew install --cask pycharm-ce','sudo snap install pycharm-community --classic','sudo snap install pycharm-community --classic'),
 (9,'JetBrains PyCharm Proffessional','winget install -e --id JetBrains.PyCharm.Professional','brew install --cask pycharm','sudo snap install pycharm-professional --classic','sudo snap install pycharm-professional --classic'),
 (10,'Visual Studio Community','winget install -e --id Microsoft.VisualStudio.2022.Community.Preview','Not Found','Not Found','Not Found'),
 (11,'Visual Studio Proffessional','winget install -e --id Microsoft.VisualStudio.2022.Professional.Preview','Not Found','Not Found','Not Found'),
 (12,'Postman','winget install -e --id Postman.Postman','brew install --cask postman','sudo snap install postman','sudo snap install postman'),
 (13,'JetBrains Space','winget install -e --id JetBrains.Space','brew install --cask jetbrains-space','sudo snap install space','sudo snap install space'),
 (14,'Postgresql','winget install -e --id PostgreSQL.PostgreSQL','brew install postgresql@14','sudo snap install postgresql10','sudo snap install postgresql10'),
 (15,'PgAdmin','winget install -e --id PostgreSQL.pgAdmin','brew install --cask pgadmin4','ManualInstallation','ManualInstallation'),
 (16,'Vim','winget install -e --id vim.vim','winget install -e --id vim.vim','sudo snap install vim-editor --beta','sudo snap install vim-editor --beta'),
 (17,'NeoVim','winget install -e --id Neovim.Neovim','brew install neovim','sudo snap install nvim --classic','sudo snap install nvim --classic'),
 (18,'Ngrok','winget install -e --id Ngrok.Ngrok','brew install --cask ngrok','sudo snap install ngrok','sudo snap install ngrok'),
 (19,'Visual Studio','Not Found','brew install --cask visual-studio','Not Found','Not Found'),
 (20,'JetBrains DataGrip','winget install -e --id JetBrains.DataGrip','brew install --cask datagrip','sudo snap install datagrip --classic','sudo snap install datagrip --classic'),
 (21,'JetBrains DataSpell','winget install -e --id JetBrains.DataSpell','brew install --cask dataspell','sudo snap install dataspell --classic','sudo snap install dataspell --classic'),
 (22,'Wget','ManualInstallation','brew install wget','ManualInstallation','ManualInstallation'),
 (23,'MySQL','winget install -e --id Oracle.MySQL','brew install mysql','sudo snap install mysql --beta','sudo snap install mysql --beta'),
 (24,'SQLite','winget install -e --id SQLite.SQLite','brew install sqlite','ManualInstallation','ManualInstallation'),
 (25,'SQLiteBrowser','winget install -e --id DBBrowserForSQLite.DBBrowserForSQLite','brew install --cask db-browser-for-sqlite','sudo snap install sqlitebrowser','sudo snap install sqlitebrowser'),
 (26,'GNU Emacs','winget install -e --id GNU.Emacs','brew install emacs','sudo snap install emacs --classic','sudo snap install emacs --classic'),
 (27,'Nginx','ManualInstallation','brew install nginx','ManualInstallation','ManualInstallation'),
 (28,'GitHub Desktop','winget install -e --id GitHub.GitHubDesktop','brew install --cask github','sudo snap install github-gui','sudo snap install github-gui'),
 (29,'GitHub CLI','winget install -e --id GitHub.cli','brew install gh','sudo snap install gh','sudo snap install gh'),
 (30,'Kubernetes','winget install -e --id Kubernetes.kubectl','brew install kubernetes-cli','sudo snap install kubectl --classic','sudo snap install kubectl --classic'),
 (31,'Slack','winget install -e --id SlackTechnologies.Slack','brew install --cask slack','sudo snap install slack','sudo snap install slack'),
 (32,'AllPackages','AllPackages','AllPackages','AllPackages','AllPackages'),
 (33,'MSBuild Tools','winget install Microsoft.VisualStudio.2022.BuildTools','Not Found','Not Found','Not Found');
INSERT INTO "RubyDevelopmentTools" ("id","Name","Windows","macOS","Linux_amd64","Linux_arm64") VALUES (1,'VSCode','winget install -e --id Microsoft.VisualStudioCode','brew install --cask visual-studio-code','sudo snap install code --classic','ManualInstallation'),
 (2,'Docker','winget install -e --id Docker.DockerDesktop','brew install --cask docker','sudo snap install docker','sudo snap install docker'),
 (3,'Git','winget install --id Git.Git -e --source winget','brew install --cask git','ManualInstallation','ManualInstallation'),
 (4,'Sublime Text','winget install -e --id SublimeHQ.SublimeText.4','brew install --cask sublime-text','sudo snap install sublime-text --classic','sudo snap install sublime-text --classic'),
 (5,'Visual Studio Community','winget install -e --id Microsoft.VisualStudio.2022.Community.Preview','Not Found','Not Found','Not Found'),
 (6,'Visual Studio Proffessional','winget install -e --id Microsoft.VisualStudio.2022.Professional.Preview','Not Found','Not Found','Not Found'),
 (7,'JetBrains RubyMine','winget install -e --id JetBrains.RubyMine','brew install --cask rubymine','sudo snap install postman','sudo snap install postman'),
 (8,'Ruby','winget install -e --id RubyInstallerTeam.Ruby.3.1','brew install ruby','sudo snap install ruby --classic','sudo snap install ruby --classic'),
 (9,'Postman','winget install -e --id Postman.Postman','brew install --cask postman','sudo snap install postman','sudo snap install postman'),
 (10,'JetBrains Space','winget install -e --id JetBrains.Space','brew install --cask jetbrains-space','sudo snap install space','sudo snap install space'),
 (11,'Postgresql','winget install -e --id PostgreSQL.PostgreSQL','brew install postgresql@14','sudo snap install postgresql10','sudo snap install postgresql10'),
 (12,'PgAdmin','winget install -e --id PostgreSQL.pgAdmin','brew install --cask pgadmin4','ManualInstallation','ManualInstallation'),
 (13,'Vim','winget install -e --id vim.vim','winget install -e --id vim.vim','sudo snap install vim-editor --beta','sudo snap install vim-editor --beta'),
 (14,'NeoVim','winget install -e --id Neovim.Neovim','brew install neovim','sudo snap install nvim --classic','sudo snap install nvim --classic'),
 (15,'Ngrok','winget install -e --id Ngrok.Ngrok','brew install --cask ngrok','sudo snap install ngrok','sudo snap install ngrok'),
 (16,'Visual Studio','Not Found','brew install --cask visual-studio','Not Found','Not Found'),
 (17,'Wget','ManualInstallation','brew install wget','ManualInstallation','ManualInstallation'),
 (18,'MySQL','winget install -e --id Oracle.MySQL','brew install mysql','sudo snap install mysql --beta','sudo snap install mysql --beta'),
 (19,'SQLite','winget install -e --id SQLite.SQLite','brew install sqlite','ManualInstallation','ManualInstallation'),
 (20,'SQLiteBrowser','winget install -e --id DBBrowserForSQLite.DBBrowserForSQLite','brew install --cask db-browser-for-sqlite','sudo snap install sqlitebrowser','sudo snap install sqlitebrowser'),
 (21,'GNU Emacs','winget install -e --id GNU.Emacs','brew install emacs','sudo snap install emacs --classic','sudo snap install emacs --classic'),
 (22,'Nginx','ManualInstallation','brew install nginx','ManualInstallation','ManualInstallation'),
 (23,'GitHub Desktop','winget install -e --id GitHub.GitHubDesktop','brew install --cask github','sudo snap install github-gui','sudo snap install github-gui'),
 (24,'GitHub CLI','winget install -e --id GitHub.cli','brew install gh','sudo snap install gh','sudo snap install gh'),
 (25,'Kubernetes','winget install -e --id Kubernetes.kubectl','brew install kubernetes-cli','sudo snap install kubectl --classic','sudo snap install kubectl --classic'),
 (26,'Slack','winget install -e --id SlackTechnologies.Slack','brew install --cask slack','sudo snap install slack','sudo snap install slack'),
 (27,'AllPackages','AllPackages','AllPackages','AllPackages','AllPackages');
INSERT INTO "RustDevelopmentTools" ("id","Name","Windows","macOS","Linux_amd64","Linux_arm64") VALUES (1,'VSCode','winget install -e --id Microsoft.VisualStudioCode','brew install --cask visual-studio-code','sudo snap install code --classic','ManualInstallation'),
 (2,'Docker','winget install -e --id Docker.DockerDesktop','brew install --cask docker','sudo snap install docker','sudo snap install docker'),
 (3,'Git','winget install --id Git.Git -e --source winget','brew install --cask git','ManualInstallation','ManualInstallation'),
 (4,'Sublime Text','winget install -e --id SublimeHQ.SublimeText.4','brew install --cask sublime-text','sudo snap install sublime-text --classic','sudo snap install sublime-text --classic'),
 (5,'Visual Studio Community','winget install -e --id Microsoft.VisualStudio.2022.Community.Preview','Not Found','Not Found','Not Found'),
 (6,'Visual Studio Proffessional','winget install -e --id Microsoft.VisualStudio.2022.Professional.Preview','Not Found','Not Found','Not Found'),
 (7,'Rust','winget install -e --id Rustlang.Rust.MSVC','brew install rust','sudo snap install rustup --classic','sudo snap install rustup --classic'),
 (8,'Postman','winget install -e --id Postman.Postman','brew install --cask postman','sudo snap install postman','sudo snap install postman'),
 (9,'JetBrains Space','winget install -e --id JetBrains.Space','brew install --cask jetbrains-space','sudo snap install space','sudo snap install space'),
 (10,'Postgresql','winget install -e --id PostgreSQL.PostgreSQL','brew install postgresql@14','sudo snap install postgresql10','sudo snap install postgresql10'),
 (11,'PgAdmin','winget install -e --id PostgreSQL.pgAdmin','brew install --cask pgadmin4','ManualInstallation','ManualInstallation'),
 (12,'Vim','winget install -e --id vim.vim','winget install -e --id vim.vim','sudo snap install vim-editor --beta','sudo snap install vim-editor --beta'),
 (13,'NeoVim','winget install -e --id Neovim.Neovim','brew install neovim','sudo snap install nvim --classic','sudo snap install nvim --classic'),
 (14,'Ngrok','winget install -e --id Ngrok.Ngrok','brew install --cask ngrok','sudo snap install ngrok','sudo snap install ngrok'),
 (15,'Visual Studio','Not Found','brew install --cask visual-studio','Not Found','Not Found'),
 (16,'Wget','ManualInstallation','brew install wget','ManualInstallation','ManualInstallation'),
 (17,'MySQL','winget install -e --id Oracle.MySQL','brew install mysql','sudo snap install mysql --beta','sudo snap install mysql --beta'),
 (18,'SQLite','winget install -e --id SQLite.SQLite','brew install sqlite','ManualInstallation','ManualInstallation'),
 (19,'SQLiteBrowser','winget install -e --id DBBrowserForSQLite.DBBrowserForSQLite','brew install --cask db-browser-for-sqlite','sudo snap install sqlitebrowser','sudo snap install sqlitebrowser'),
 (20,'GNU Emacs','winget install -e --id GNU.Emacs','brew install emacs','sudo snap install emacs --classic','sudo snap install emacs --classic'),
 (21,'Nginx','ManualInstallation','brew install nginx','ManualInstallation','ManualInstallation'),
 (22,'GitHub Desktop','winget install -e --id GitHub.GitHubDesktop','brew install --cask github','sudo snap install github-gui','sudo snap install github-gui'),
 (23,'GitHub CLI','winget install -e --id GitHub.cli','brew install gh','sudo snap install gh','sudo snap install gh'),
 (24,'Kubernetes','winget install -e --id Kubernetes.kubectl','brew install kubernetes-cli','sudo snap install kubectl --classic','sudo snap install kubectl --classic'),
 (25,'Slack','winget install -e --id SlackTechnologies.Slack','brew install --cask slack','sudo snap install slack','sudo snap install slack'),
 (26,'AllPackages','AllPackages','AllPackages','AllPackages','AllPackages'),
 (27,'MSBuild Tools','winget install Microsoft.VisualStudio.2022.BuildTools','Not Found','Not Found','Not Found');
INSERT INTO "DevelopmentPacks" ("id","Language") VALUES (1,'PythonDevelopmentTools'),
 (2,'JavaScriptDevelopmentTools'),
 (3,'CppDevelopmentTools'),
 (4,'JavaDevelopmentTools'),
 (5,'GoDevelopmentTools'),
 (6,'RustDevelopmentTools'),
 (7,'RubyDevelopmentTools'),
 (8,'CDevelopmentTools'),
 (9,'CSDevelopmentTools'),
 (10,'PHPDevelopmentTools'),
 (11,'KotlinDevelopmentTools');
INSERT INTO "PackagesFromSource_Linux_amd64" ("id","Name","Url","Command","apt","yum","dnf","apk","pacman","zypper") VALUES (1,'vcpkg','https://github.com/microsoft/vcpkg','git clone https://github.com/microsoft/vcpkg && cd vcpkg && ./bootstrap-vcpkg.sh -disableMetrics','sudo apt update -y && sudo apt-get install curl zip unzip tar','sudo yum update -y && sudo yum install curl zip unzip tar','sudo dnf update -y && sudo dnf install curl zip unzip tar','sudo apk upgrade && sudo apk add build-base cmake ninja zip unzip curl','sudo pacman -Syu && sudo pacman -S curl zip unzip tar cmake ninja','sudo zypper install curl zip unzip tar'),
 (2,'Make','Empty','Empty','sudo apt update -y && sudo apt install make -y','sudo yum update -y && sudo yum install make -y','sudo dnf -y update && sudo dnf -y install make','Empty','sudo pacman -Syu && sudo pacman -S make','Empty'),
 (3,'PHP','Empty','Empty','sudo apt update -y && sudo apt install php -y && sudo apt install libapache2-mod-php -y','sudo yum update -y &&  sudo  yum install epel-release yum-utils -y && sudo yum install http://rpms.remirepo.net/enterprise/remi-release-7.rpm -y &&  sudo yum-config-manager --enable remi-php74 && sudo yum update -y && sudo yum install php -y && sudo yum install php-fpm php-curl php-cli php-json php-mysql php-opcache php-dom php-exif php-fileinfo php-zip php-mbstring php-hash php-imagick php-openssl php-pcre php-xml php-bcmath php-filter php-pear php-gd php-mcrypt php-intl php-iconv php-zlib php-xmlreader -y','sudo dnf -y update && sudo dnf -y install dnf-plugins-core && sudo dnf config-manager --set-enabled remi && sudo dnf module reset php -y && sudo dnf module -y install php:remi-8.0 && sudo dnf -y install php-cli php-fpm php-mysqlnd php-zip php-devel php-gd php-mcrypt php-mbstring php-curl php-xml php-pear php-bcmath php-json && sudo systemctl enable --now php-fpm','Empty','sudo pacman -Sy archlinux-keyring && sudo pacman-key --populate archlinux && sudo pacman -Syu && sudo pacman -S php && sudo pacman -S php-apache php-cgi php-fpm php-gd  php-embed php-intl php-redis php-snmp','Empty'),
 (4,'Wget','Empty','Empty','sudo apt update -y && sudo apt install wget -y','sudo yum install wget','sudo dnf -y update && sudo dnf install wget','Empty','sudo pacman -Syu && sudo pacman -S wget','sudo zypper install wget'),
 (5,'Python 3.9','Empty','Empty','sudo apt update -y && sudo apt upgrade -y && sudo apt install wget build-essential libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev libffi-dev zlib1g-dev && sudo wget https://www.python.org/ftp/python/3.9.6/Python-3.9.6.tgz && sudo tar xzf Python-3.9.6.tgz && cd Python-3.9.6 && ./configure --enable-optimizations && sudo make -j 2 && sudo make altinstall','sudo yum update -y && sudo yum install epel-release -y && sudo yum install python-pip -y && sudo yum install gcc openssl-devel bzip2-devel libffi-devel zlib-devel -y && sudo wget https://www.python.org/ftp/python/3.9.6/Python-3.9.6.tgz && sudo tar -xvf Python-3.9.6.tgz && ./configure --enable-optimizations && sudo make && sudo make altinstall','sudo dnf -y update && sudo dnf groupinstall ''development tools'' && sudo dnf install wget openssl-devel bzip2-devel libffi-devel &&  sudo wget https://www.python.org/ftp/python/3.9.6/Python-3.9.6.tgz && sudo tar -xvf Python-3.9.6.tgz && cd Python-3.9.6 &&  ./configure --enable-optimizations && sudo make && sudo make altinstall','Empty','Empty','Empty'),
 (6,'Python 3.10','Empty','Empty','sudo apt update -y && sudo apt upgrade -y && sudo apt install wget build-essential libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev libffi-dev zlib1g-dev && sudo wget https://www.python.org/ftp/python/3.10.12/Python-3.10.12.tgz && sudo tar xzf Python-3.10.12.tgz && cd Python-3.10.12 && ./configure --enable-optimizations && sudo make -j 2 && sudo make altinstall','sudo yum update -y && sudo yum install epel-release -y && sudo yum install python-pip -y && sudo yum install gcc openssl-devel bzip2-devel libffi-devel zlib-devel -y && sudo wget https://www.python.org/ftp/python/3.10.12/Python-3.10.12.tgz && sudo tar -xvf Python-3.10.12.tgz && ./configure --enable-optimizations && sudo make && sudo make altinstall','sudo dnf -y update && sudo dnf groupinstall ''development tools'' && sudo dnf install wget openssl-devel bzip2-devel libffi-devel &&  sudo wget https://www.python.org/ftp/python/3.10.12/Python-3.10.12.tgz && sudo  tar -xvf Python-3.10.12.tgz && cd Python-3.10.12 && ./configure --enable-optimizations && sudo make && sudo make altinstall','Empty','Empty','Empty'),
 (7,'Python 3.11','Empty','Empty','sudo apt update -y && sudo apt upgrade -y && sudo apt install wget build-essential libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev libffi-dev zlib1g-dev && sudo wget https://www.python.org/ftp/python/3.11.4/Python-3.11.4.tgz && sudo tar xzf Python-3.11.4.tgz && cd Python-3.11.4 && ./configure --enable-optimizations && sudo make -j 2 && sudo make altinstall','sudo yum update -y && sudo yum install epel-release -y && sudo yum install python-pip -y && sudo yum install gcc openssl-devel bzip2-devel libffi-devel zlib-devel -y && sudo wget https://www.python.org/ftp/python/3.11.4/Python-3.11.4.tgz && sudo tar -xvf Python-3.11.4.tgz && ./configure --enable-optimizations && sudo make && sudo make altinstall','sudo dnf -y update && sudo dnf groupinstall ''development tools'' && sudo dnf install wget openssl-devel bzip2-devel libffi-devel &&  sudo wget https://www.python.org/ftp/python/3.11.4/Python-3.11.4.tgz && sudo tar -xvf Python-3.11.4.tgz && cd Python-3.11.4 && ./configure --enable-optimizations && sudo make && sudo make altinstall','Empty','Empty','Empty'),
 (8,'Nginx','Empty','Empty','sudo apt update -y && sudo apt install nginx -y','sudo yum install epel-release -y && sudo yum update -y && sudo yum install nginx','sudo dnf -y update && sudo dnf install nginx && sudo systemctl enable nginx && sudo systemctl start nginx','Empty','sudo pacman -Syu && sudo pacman -S nginx-mainline && sudo systemctl enable --now nginx','Empty'),
 (9,'snap','Empty','Empty','sudo apt update && sudo apt-get install -yqq daemonize dbus-user-session fontconfig && sudo apt install snap snapd && sudo ln -s /var/lib/snapd/snap /snap && sudo systemctl enable snapd.service && sudo systemctl start snapd.service','sudo yum update -y && sudo yum install snapd -y && sudo systemctl enable --now snapd.socket && sudo ln -s /var/lib/snapd/snap /snap','sudo dnf update -y && sudo dnf install snap snapd fuse squashfuse kernel-modules && sudo ln -s /var/lib/snapd/snap /snap && sudo systemctl enable snapd.service && sudo systemctl start snapd.service','Empty','sudo pacman -Syu && sudo pacman -S snapd && sudo ln -s /var/lib/snapd/snap /snap && sudo systemctl enable --now snapd.socket && sudo systemctl start snapd.service','sudo zypper addrepo http://download.opensuse.org/repositories/system:/snappy/openSUSE_Leap_42.2/ snappy && sudo zypper install snapd && sudo systemctl enable --now snapd.socket'),
 (10,'gcc','Empty','Empty','sudo apt update -y && sudo apt install gcc','sudo yum update -y && sudo yum install gcc -y','sudo dnf update -y && sudo dnf install gcc -y','Empty','sudo pacman -Syu && sudo pacman -Sy gcc','sudo zypper install gcc-c++ && sudo zypper install gcc gcc-fortran'),
 (11,'g++','Empty','Empty','sudo apt update -y && sudo apt install g++ -y','sudo yum update -y && sudo yum install gcc-c++ -y','sudo dnf update -y && sudo dnf install gcc-c++ -y','Empty','sudo pacman -Syu && sudo pacman -Sy gcc','sudo zypper install gcc-c++ && sudo zypper install gcc gcc-fortran'),
 (12,'Code::Blocks','Empty','Empty','sudo add-apt-repository ppa:damien-moore/codeblocks-stable && sudo apt-get update -y && sudo apt-get install codeblocks codeblocks-contrib -y','sudo yum update -y && sudo yum install codeblocks.x86_64 -y','sudo dnf update -y && sudo dnf install codeblocks','Empty','sudo pacman -Syu && sudo pacman -S make wget zip xterm && sudo  wget https://github.com/wxWidgets/wxWidgets/releases/download/v3.0.3/wxWidgets-3.0.3.tar.bz2 && sudo  tar -x -f wxWidgets-3.0.3.tar.bz2 &&  cd wxWidgets-3.0.3 && sudo  ./configure --enable-unicode --enable-monolithic --enable-debug --enable-shared && sudo make && sudo make install && sudo pacman -S svn hunspell boost && cd ~ && svn checkout https://svn.code.sf.net/p/codeblocks/code/trunk codeblocks-code && cd codeblocks-code && sudo ./bootstrap && sudo ./configure  --with-contrib-plugins=all,-FileManager --prefix=/opt/codeblocks && sudo make && sudo make install && LD_LIBRARY_PATH=/usr/local/bin /opt/codeblocks/bin/codeblocks
','zypper addrepo https://download.opensuse.org/repositories/devel:tools:ide/openSUSE_Factory/devel:tools:ide.repo && zypper refresh && zypper install codeblocks'),
 (13,'Google Chrome','Empty','Empty','sudo apt update -y && sudo apt install wget -y && sudo wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && sudo apt install ./google-chrome-stable_current_amd64.deb && sudo rm ./google-chrome-stable_current_amd64.deb','Empty','Empty','Empty','Empty','Empty'),
 (14,'Git','Empty','Empty','sudo apt update -y && sudo apt install git','sudo yum update -y && sudo yum install git','sudo dnf update -y && sudo dnf install git-all','sudo apk upgrade && sudo apk add git','sudo pacman -Syu && sudo pacman -S git','sudo zypper install git');
INSERT INTO "PackagesFromSource_Linux_arm64" ("id","Name","Url","Command","apt","yum","dnf","apk","pacman","zypper") VALUES (1,'Code::Blocks','Empty','Empty','sudo add-apt-repository ppa:damien-moore/codeblocks-stable && sudo apt-get update -y && sudo apt-get install codeblocks codeblocks-contrib -y','sudo yum update -y && sudo yum install codeblocks.x86_64 -y','sudo dnf update -y && sudo dnf install codeblocks','Empty','sudo pacman -Syu && sudo pacman -S make wget zip xterm && sudo  wget https://github.com/wxWidgets/wxWidgets/releases/download/v3.0.3/wxWidgets-3.0.3.tar.bz2 && sudo  tar -x -f wxWidgets-3.0.3.tar.bz2 &&  cd wxWidgets-3.0.3 && sudo  ./configure --enable-unicode --enable-monolithic --enable-debug --enable-shared && sudo make && sudo make install && sudo pacman -S svn hunspell boost && cd ~ && svn checkout https://svn.code.sf.net/p/codeblocks/code/trunk codeblocks-code && cd codeblocks-code && sudo ./bootstrap && sudo ./configure  --with-contrib-plugins=all,-FileManager --prefix=/opt/codeblocks && sudo make && sudo make install && LD_LIBRARY_PATH=/usr/local/bin /opt/codeblocks/bin/codeblocks
','zypper addrepo https://download.opensuse.org/repositories/devel:tools:ide/openSUSE_Factory/devel:tools:ide.repo && zypper refresh && zypper install codeblocks'),
 (2,'snap','Empty','Empty','sudo apt update && sudo apt-get install -yqq daemonize dbus-user-session fontconfig && sudo apt install snap snapd && sudo ln -s /var/lib/snapd/snap /snap && sudo systemctl enable snapd.service && sudo systemctl start snapd.service','sudo yum update -y && sudo yum install snapd -y && sudo systemctl enable --now snapd.socket && sudo ln -s /var/lib/snapd/snap /snap','sudo dnf update -y && sudo dnf install snap snapd fuse squashfuse kernel-modules && sudo ln -s /var/lib/snapd/snap /snap && sudo systemctl enable snapd.service && sudo systemctl start snapd.service','Empty','sudo pacman -Syu && sudo pacman -S snapd && sudo ln -s /var/lib/snapd/snap /snap && sudo systemctl enable --now snapd.socket && sudo systemctl start snapd.service','sudo zypper addrepo http://download.opensuse.org/repositories/system:/snappy/openSUSE_Leap_42.2/ snappy && sudo zypper install snapd && sudo systemctl enable --now snapd.socket'),
 (3,'g++','Empty','Empty','sudo apt update -y && sudo apt install g++ -y','sudo yum update -y && sudo yum install gcc-c++ -y','sudo dnf update -y && sudo dnf install gcc-c++ -y','Empty','sudo pacman -Syu && sudo pacman -Sy gcc','sudo zypper install gcc-c++ && sudo zypper install gcc gcc-fortran'),
 (4,'gcc','Empty','Empty','sudo apt update -y && sudo apt install gcc','sudo yum update -y && sudo yum install gcc -y','sudo dnf update -y && sudo dnf install gcc -y','Empty','sudo pacman -Syu && sudo pacman -Sy gcc','sudo zypper install gcc-c++ && sudo zypper install gcc gcc-fortran'),
 (5,'Git','Empty','Empty','sudo apt update -y && sudo apt install git','sudo yum update -y && sudo yum install git','sudo dnf update -y && sudo dnf install git-all','sudo apk upgrade && sudo apk add git','sudo pacman -Syu && sudo pacman -S git','sudo zypper install git'),
 (6,'Make','Empty','Empty','sudo apt update -y && sudo apt install make -y','sudo yum update -y && sudo yum install make -y','sudo dnf -y update && sudo dnf -y install make','Empty','sudo pacman -Syu && sudo pacman -S make','Empty'),
 (7,'Nginx','Empty','Empty','sudo apt update -y && sudo apt install nginx -y','sudo yum install epel-release -y && sudo yum update -y && sudo yum install nginx','sudo dnf -y update && sudo dnf install nginx && sudo systemctl enable nginx && sudo systemctl start nginx','Empty','sudo pacman -Syu && sudo pacman -S nginx-mainline && sudo systemctl enable --now nginx','Empty'),
 (8,'PHP','Empty','Empty','sudo apt update -y && sudo apt install php -y && sudo apt install libapache2-mod-php -y','sudo yum update -y &&  sudo  yum install epel-release yum-utils -y && sudo yum install http://rpms.remirepo.net/enterprise/remi-release-7.rpm -y &&  sudo yum-config-manager --enable remi-php74 && sudo yum update -y && sudo yum install php -y && sudo yum install php-fpm php-curl php-cli php-json php-mysql php-opcache php-dom php-exif php-fileinfo php-zip php-mbstring php-hash php-imagick php-openssl php-pcre php-xml php-bcmath php-filter php-pear php-gd php-mcrypt php-intl php-iconv php-zlib php-xmlreader -y','sudo dnf -y update && sudo dnf -y install dnf-plugins-core && sudo dnf config-manager --set-enabled remi && sudo dnf module reset php -y && sudo dnf module -y install php:remi-8.0 && sudo dnf -y install php-cli php-fpm php-mysqlnd php-zip php-devel php-gd php-mcrypt php-mbstring php-curl php-xml php-pear php-bcmath php-json && sudo systemctl enable --now php-fpm','Empty','sudo pacman -Sy archlinux-keyring && sudo pacman-key --populate archlinux && sudo pacman -Syu && sudo pacman -S php && sudo pacman -S php-apache php-cgi php-fpm php-gd  php-embed php-intl php-redis php-snmp','Empty'),
 (9,'Wget','Empty','Empty','sudo apt update -y && sudo apt install wget -y','sudo yum install wget','sudo dnf -y update && sudo dnf install wget','Empty','sudo pacman -Syu && sudo pacman -S wget','sudo zypper install wget'),
 (10,'Google Chrome','Empty','Empty','sudo apt update -y && sudo apt install wget -y && sudo wget https://dl.google.com/linux/direct/google-chrome-stable_current_arm64.deb && sudo apt install ./google-chrome-stable_current_arm64.deb && sudo rm ./google-chrome-stable_current_arm64.deb','Empty','Empty','Empty','Empty','Empty'),
 (11,'Python 3.10','Empty','Empty','sudo apt update -y && sudo apt upgrade -y && sudo apt install wget build-essential libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev libffi-dev zlib1g-dev && sudo wget https://www.python.org/ftp/python/3.10.12/Python-3.10.12.tgz && sudo tar xzf Python-3.10.12.tgz && cd Python-3.10.12 && ./configure --enable-optimizations && sudo make -j 2 && sudo make altinstall','sudo yum update -y && sudo yum install epel-release -y && sudo yum install python-pip -y && sudo yum install gcc openssl-devel bzip2-devel libffi-devel zlib-devel -y && sudo wget https://www.python.org/ftp/python/3.10.12/Python-3.10.12.tgz && sudo tar -xvf Python-3.10.12.tgz && ./configure --enable-optimizations && sudo make && sudo make altinstall','sudo dnf -y update && sudo dnf groupinstall ''development tools'' && sudo dnf install wget openssl-devel bzip2-devel libffi-devel &&  sudo wget https://www.python.org/ftp/python/3.10.12/Python-3.10.12.tgz && sudo  tar -xvf Python-3.10.12.tgz && cd Python-3.10.12 && ./configure --enable-optimizations && sudo make && sudo make altinstall','Empty','Empty','Empty'),
 (12,'Python 3.11','Empty','Empty','sudo apt update -y && sudo apt upgrade -y && sudo apt install wget build-essential libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev libffi-dev zlib1g-dev && sudo wget https://www.python.org/ftp/python/3.11.4/Python-3.11.4.tgz && sudo tar xzf Python-3.11.4.tgz && cd Python-3.11.4 && ./configure --enable-optimizations && sudo make -j 2 && sudo make altinstall','sudo yum update -y && sudo yum install epel-release -y && sudo yum install python-pip -y && sudo yum install gcc openssl-devel bzip2-devel libffi-devel zlib-devel -y && sudo wget https://www.python.org/ftp/python/3.11.4/Python-3.11.4.tgz && sudo tar -xvf Python-3.11.4.tgz && ./configure --enable-optimizations && sudo make && sudo make altinstall','sudo dnf -y update && sudo dnf groupinstall ''development tools'' && sudo dnf install wget openssl-devel bzip2-devel libffi-devel &&  sudo wget https://www.python.org/ftp/python/3.11.4/Python-3.11.4.tgz && sudo tar -xvf Python-3.11.4.tgz && cd Python-3.11.4 && ./configure --enable-optimizations && sudo make && sudo make altinstall','Empty','Empty','Empty'),
 (13,'Python 3.9','Empty','Empty','sudo apt update -y && sudo apt upgrade -y && sudo apt install wget build-essential libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev libffi-dev zlib1g-dev && sudo wget https://www.python.org/ftp/python/3.9.6/Python-3.9.6.tgz && sudo tar xzf Python-3.9.6.tgz && cd Python-3.9.6 && ./configure --enable-optimizations && sudo make -j 2 && sudo make altinstall','sudo yum update -y && sudo yum install epel-release -y && sudo yum install python-pip -y && sudo yum install gcc openssl-devel bzip2-devel libffi-devel zlib-devel -y && sudo wget https://www.python.org/ftp/python/3.9.6/Python-3.9.6.tgz && sudo tar -xvf Python-3.9.6.tgz && ./configure --enable-optimizations && sudo make && sudo make altinstall','sudo dnf -y update && sudo dnf groupinstall ''development tools'' && sudo dnf install wget openssl-devel bzip2-devel libffi-devel &&  sudo wget https://www.python.org/ftp/python/3.9.6/Python-3.9.6.tgz && sudo tar -xvf Python-3.9.6.tgz && cd Python-3.9.6 &&  ./configure --enable-optimizations && sudo make && sudo make altinstall','Empty','Empty','Empty'),
 (14,'vcpkg','https://github.com/microsoft/vcpkg','git clone https://github.com/microsoft/vcpkg && cd vcpkg && ./bootstrap-vcpkg.sh -disableMetrics','sudo apt update -y && sudo apt-get install curl zip unzip tar','sudo yum update -y && sudo yum install curl zip unzip tar','sudo dnf update -y && sudo dnf install curl zip unzip tar','sudo apk upgrade && sudo apk add build-base cmake ninja zip unzip curl','sudo pacman -Syu && sudo pacman -S curl zip unzip tar cmake ninja','sudo zypper install curl zip unzip tar');
INSERT INTO "PackagesFromSource_Windows" ("id","Name","Url","Command","HomeURL") VALUES (1,'vcpkg','Empty','git clone https://github.com/microsoft/vcpkg && cd vcpkg && .\bootstrap-vcpkg.bat -disableMetrics','https://github.com/microsoft/vcpkg'),
 (2,'Make','https://github.com/DeepForge-Tech/DeepForge-Toolset-Packages/releases/download/Packages/Make_3.81.zip','Empty','https://github.com/DeepForge-Tech/DeepForge-Toolset-Packages/releases/download/Packages/'),
 (3,'PHP','https://github.com/DeepForge-Tech/DeepForge-Toolset-Packages/releases/download/Packages/php-8.3.8-Win32-vs16-x64.zip','Empty','https://windows.php.net/downloads/releases/'),
 (4,'Eclipse IDE','https://github.com/DeepForge-Tech/DeepForge-Toolset-Packages/releases/download/Packages/eclipse-scout-2024-03-M3-win32-x86_64.zip','Empty','https://mirrors.jevincanders.net/eclipse/technology/epp/downloads/release/2024-03/M3/'),
 (5,'Kotlin','https://github.com/DeepForge-Tech/DeepForge-Toolset-Packages/releases/download/Packages/kotlin-compiler-1.8.22.zip','Empty','https://github.com/JetBrains/kotlin/releases/download/v1.8.22/'),
 (6,'Wget','https://github.com/DeepForge-Tech/DeepForge-Toolset-Packages/releases/download/Packages/wget.zip','Empty','https://eternallybored.org/misc/wget/1.21.4/64/'),
 (7,'Nginx','https://github.com/DeepForge-Tech/DeepForge-Toolset-Packages/releases/download/Packages/nginx-1.25.1.zip','Empty','http://nginx.org/download/'),
 (8,'Redis','https://github.com/DeepForge-Tech/DeepForge-Toolset-Packages/releases/download/Packages/Redis-x64-3.0.504.zip','Empty','https://github.com/microsoftarchive/redis/releases/download/win-3.0.504/');
INSERT INTO "OS_Commands" ("id","Name","Windows","Linux","macOS") VALUES (1,'Reboot','shutdown -r -t 0','sudo shutdown -r now','sudo shutdown -r now');
INSERT INTO "SupportedOS" ("id","Name","PackageManager") VALUES (1,'Ubuntu','apt'),
 (2,'Debian GNU/Linux','apt'),
 (3,'Kali GNU/Linux','apt'),
 (4,'CentOS Linux','dnf'),
 (5,'Alpine Linux','apk'),
 (6,'Fedora Linux','yum'),
 (7,'Arch Linux','pacman'),
 (8,'Manjaro Linux','pacman'),
 (9,'Red Hat Enterprise Linux Server','yum'),
 (10,'Linux Mint','apt'),
 (11,'Raspbian GNU/Linux','apt');
COMMIT;
