name: C/C++ CI

on:
  push:
    branches: 
      - "dev"
      - "master"
  pull_request:
    branches: 
      - "dev"
      - "master"

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install libraries
      run: sudo add-apt-repository universe && sudo apt update && sudo apt upgrade && sudo apt install curl && sudo apt-get install libcurl4-openssl-dev libgtest-dev googletest google-mock libgmock-dev libtbb-dev libjsoncpp-dev
    - name: Building project
      run: mkdir build && cd build && cmake .. && cmake --build .
    - name: Testing project
      run: cd build && ctest
  build_macOS_12:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Install HomeBrew
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - name: Install libraries
        run: rm /usr/local/bin/2to3-3.12 && brew  install jsoncpp && brew install sqlite && brew install sqlite-utils && brew install fmt && brew install clang-format && brew install curl && brew install googletest && brew install gcc && brew install zlib && brew install cmake && brew install libzip
      - name: Building project
        run: mkdir build && cd build && cmake .. && cmake --build .
      - name: Testing project
        run: cd build && ctest
  build_macOS_13:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - name: Install HomeBrew
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - name: Install libraries
        run: rm /usr/local/bin/2to3-3.12 && brew  install jsoncpp && brew install sqlite && brew install sqlite-utils && brew install fmt && brew install clang-format && brew install curl && brew install googletest && brew install gcc && brew install zlib && brew install cmake && brew install libzip
      - name: Building project
        run: mkdir build && cd build && cmake .. && cmake --build .
      - name: Testing project
        run: cd build && ctest